In [1]:
import importlib
import time
import numpy as np

from b_Closed_form import BS_greeks
from c_MC import MC_BS_greeks_gpu, MC_heston_greeks_gpu
from d_FDM import FDM_BS_greeks, FDM_heston_greeks
import e_3_CVAE_greek
importlib.reload(e_3_CVAE_greek)
from e_3_CVAE_greek import CVAE_greeks
from e_0_generate import generate_BS_params, generate_heston_params

In [91]:
#closed_form
# eta = (S0, K, r, sigma, T)

greek_key = ['delta', 'vega', 'rho', 'theta']
bs_eta = (1.0, 1.0, 0.03, np.sqrt(0.05), 1.5)
type = 'put'
relative_step = 0.01

vanilla = BS_greeks(bs_eta, type=type, relative_step=relative_step)
barrier = BS_greeks(bs_eta, B=0.5, type=type, relative_step=relative_step)

for key in greek_key:
    print(f"Vanilla Average {key}: {np.mean(vanilla[key]):.6f}")
    print(f"Barrier Average {key}: {np.mean(barrier[key]):.6f}")
    print(f"================================")

Vanilla Average delta: -0.381613
Barrier Average delta: -0.324582
================================
Vanilla Average vega: 0.466928
Barrier Average vega: 0.281394
================================
Vanilla Average rho: -0.701333
Barrier Average rho: -0.621566
================================
Vanilla Average theta: -0.020776
Barrier Average theta: -0.008698
================================

# MC

In [23]:
# MC bs
time_result = []
greek_result = {n: [] for n in ['delta', 'vega', 'rho', 'theta']}
greek_key = ['delta', 'vega', 'rho', 'theta']
bs_eta = (1.0, 1.0, 0.03, np.sqrt(0.05), 1.5)

for i in range(50):
    start = time.time()
    bs_result = MC_BS_greeks_gpu(
        bs_eta,
        B=0.8, #or None
        opt_type='put',
        n_paths=1_000,
        dt=0.001,
        seed=1234 + i*100,
        antithetic=True,
        relative_step=0.01
    )
    time_result.append(time.time() - start)
    for key in greek_key:
        greek_result[key].append(bs_result[key])

print(f"Average time: {np.mean(time_result):.6f}s")
for key in greek_key:
    print(f"Average {key}: {np.mean(greek_result[key]):.6f}")
    print(f"Std {key}: {np.std(greek_result[key]):.6f}")

Average time: 0.653659s
Average delta: 0.025823
Std delta: 0.040049
Average vega: -0.088979
Std vega: 0.058177
Average rho: -0.030891
Std rho: 0.060887
Average theta: 0.005621
Std theta: 0.026472

In [50]:
bs_result['details']['delta']['h'],bs_result['details']['vega']['h'],bs_result['details']['rho']['h'],bs_result['details']['theta']['h']

(np.float64(0.01), np.float64(0.00223606797749979), np.float64(0.0003), 0.015)

In [26]:
# MC hes
time_result = []
greek_result = {n: [] for n in ['delta', 'v0', 'rho', 'theta']}
greek_key = ['delta', 'v0', 'rho', 'theta']
hes_eta = (1.0, 1.0, 0.03, 2.0, 0.05, 0.5, -0.7, 0.04, 1.5)

for i in range(50):
    start = time.time()
    heston_result = MC_heston_greeks_gpu(
        hes_eta,
        B=0.8,
        opt_type='put',
        n_paths=1_000,
        dt=0.001,
        seed=1234 + i*100,
        antithetic=True,
        relative_step=0.01
    )
    time_result.append(time.time() - start)
    for key in greek_key:
        greek_result[key].append(heston_result[key])

print(f"Average time: {np.mean(time_result):.6f}s")
for key in greek_key:
    print(f"Average {key}: {np.mean(greek_result[key]):.6f}")
    print(f"Std {key}: {np.std(greek_result[key]):.6f}")

Average time: 1.249051s
Average delta: -0.014547
Std delta: 0.025994
Average v0: -0.034124
Std v0: 0.038966
Average rho: -0.052262
Std rho: 0.045871
Average theta: 0.003127
Std theta: 0.017991

In [52]:
heston_result['details']['delta']['h'],heston_result['details']['v0']['h'],heston_result['details']['rho']['h'],heston_result['details']['theta']['h']

(np.float64(0.01), np.float64(0.0004), np.float64(0.0003), 0.015)

# FDM

In [27]:
# FDM
bs_eta = [1.0, 1.0, 0.03, np.sqrt(0.05), 1.5]
start = time.time()
bs_greeks = FDM_BS_greeks(
    bs_eta,
    B=0.8,
    opt_type="put",
    solver_kwargs={"S_max": 4.0, "dS": 0.005, "dt": 0.0005},
)
print(f"FDM BS time: {time.time() - start:.6f}s")

FDM BS time: 0.471557s

In [67]:
print(bs_greeks['h'])
print(bs_greeks['delta'])
print(bs_greeks['vega'])
print(bs_greeks['rho'])
print(bs_greeks['theta'])

{'S0': 0.01, 'r': 0.0003, 'sigma': 0.00223606797749979, 'T': 0.015}
0.01522695264769081
-0.08877840196882691
-0.03725503403568971
0.007241889617288997

In [ ]:
hes_eta = [1.0, 1.0, 0.03, 2.0, 0.05, 0.5, -0.7, 0.04, 1.5]
start = time.time()
hes_greeks1 = FDM_heston_greeks(
    hes_eta,
    B=None,
    opt_type="put",
    greeks=("delta", "rho", "v0", "theta"),
    solver_kwargs={"S_max": 4.0, "v_max": 1.5, "dS": 0.01, "dv": 0.0001, "dt": 0.01}, # 
)
print(f"FDM BS time: {time.time() - start:.6f}s")

print(hes_greeks1['h'])
print(hes_greeks1['delta'])
print(hes_greeks1['v0'])
print(hes_greeks1['rho'])
print(hes_greeks1['theta'])

Calculating base

# CVAE

In [2]:
from e_2_CVAE import CVAE
import e_2_CVAE_UT
import torch
if not(torch.cuda.is_available()):
    raise ValueError("CUDA is not available")
device = torch.device("cuda")

In [22]:
validate_samples= False
valid_resample  = validate_samples
multiple        = 50

In [3]:
# bs CVAE training settings
model_type = 'bs'
dim_z       = 2 # 2, 4, 8
hidden_dims = [1024, 1024, 512, 256] # [128, 128, 64], [512, 256, 128], [1024, 512, 256], [1024, 1024, 512, 256], [1024, 1024, 1024, 1024, 1024]
batch_size  = 16384 # 1024, 2048, 128-4096, 8192, 16384, 32768, 65536
bn_chunks   = None # None or num
use_bn      = True if bn_chunks is not None else False
lr          = 2e-5 # 수렴속도 1e-4 < 1e-5
l1          = 11
lr2         = 2e-6
l2          = 12
lr3         = 1e-6
l3          = 13
beta        = 1
validation_chunk_idxs = [15,24,78]
val_every_chunks = 97
memory_on_gpu = True
warmup_chunks = None # None or num

num_chunks  = 1164
cvae_type = "base" # "base" or "barr_weight"(exponential), "normal_weight", "add_put_loss"
weight_mode = "barrier_put" # barr_weight : "barrier_put", "barrier_near" / normal_weight, add_put_loss: "barrier_put", "all_put"
weight_alpha = 0.0
weight_alpha2 = None
weight_h = 0.01 # 0.01, 0.03, 0.04
weight_normalize = True
resume_path = None # or None 이어서 학습하고 싶을 때

save_path   = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{batch_size}_{bn_chunks}_{l1}-{lr}_{l2}-{lr2}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}.pt"
result_base_path = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{batch_size}_{bn_chunks}_{l1}-{lr}_{l2}-{lr2}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}"


ckpt = torch.load(save_path, map_location=device, weights_only=False)
cvae = CVAE(
    dim_x=ckpt["dim_x"],
    dim_eta=ckpt["dim_eta"],
    dim_z=ckpt["dim_z"],
    hidden_dims=ckpt["hidden_dims"],
    use_bn=ckpt.get("use_bn", False),
).to(device)

state_dict = ckpt["model_state"]
if any(k.startswith("module.") for k in state_dict):
    state_dict = {k.replace("module.", "", 1): v for k, v in state_dict.items()}

cvae.load_state_dict(state_dict)
cvae.eval()

bs_cvae, bs_ckpt = cvae, ckpt

In [12]:
# bs_bbc
# CVAE training settings
model_type = 'bs_bbc' # bs_bbc, hes_bbc
dim_z       = 2 # 2, 4, 8
hidden_dims = [1024,1024,1024,512] # [128, 128, 64], [512, 256, 128], [1024, 512, 256], [1024, 1024, 512, 256], [1024, 1024, 1024, 1024, 1024]
batch_size  = 16384 # 1024, 2048, 128-4096, 8192, 16384, 32768, 65536
bn_chunks   = None # None or num
use_bn      = True if bn_chunks is not None else False
lr          = 2e-5 # 수렴속도 1e-4 < 1e-5
l1          = 10
lr2         = 2e-6
l2          = 11
lr3         = 1e-6
l3          = 13
beta        = 1
validation_chunk_idxs = [15,24,78]
val_every_chunks = 97
memory_on_gpu = True
warmup_chunks = None # None or num
cvae_type = "base" # "base" or "barr_weight"(exponential), "normal_weight", "add_put_loss"
weight_mode = "barrier_put" # barr_weight : "barrier_put", "barrier_near" / normal_weight, add_put_loss: "barrier_put", "all_put"
weight_alpha = 0.0
weight_alpha2 = None
weight_h = 0.01 # 0.01, 0.03, 0.04
weight_normalize = True
resume_path = None # or None 이어서 학습하고 싶을 때

num_chunks  = 1164
multiple = 0  # 0이면 비활성화, 10이면 S_T >= 10*S0 폐기 후 재추출
nvp_multiple = 10
multiple_suffix = f"_multiple{multiple:g}" if multiple > 0 else ""

validate_samples = False
valid_resample = False
mt_corr = False
continuous_layer = 0
target_parameterization = "mt" # mt, ut

if cvae_type == "base":
# bs
#     save_path   = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
# _{lr}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}.pt"
#     result_base_path = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
# _{lr}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}"
    save_path   = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{l1}-{lr}_{l2}-{lr2}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}.pt"
    result_base_path = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{l1}-{lr}_{l2}-{lr2}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}"


if 'base' in save_path:
    raise ValueError("base는 save_path에 포함되면 안됨.")

n_samples = 10000 # n_samples= 1k, 10k, 100k
if n_samples % 2 != 0:
    raise ValueError("n_samples should be an even number for antithetic sampling")


if "ut" in save_path:
    ckpt = torch.load(save_path, map_location=device, weights_only=False)
    cvae = e_2_CVAE_UT.CVAE.from_checkpoint(ckpt).to(device)
else:
    ckpt = torch.load(save_path, map_location=device, weights_only=False)
    cvae = CVAE(
        dim_x=ckpt["dim_x"],
        dim_eta=ckpt["dim_eta"],
        dim_z=ckpt["dim_z"],
        hidden_dims=ckpt["hidden_dims"],
        use_bn=ckpt.get("use_bn", False),
        residual_blocks=ckpt.get("residual_blocks", 0),
    ).to(device)
    
    state_dict = ckpt["model_state"]
    if any(k.startswith("module.") for k in state_dict):
        state_dict = {k.replace("module.", "", 1): v for k, v in state_dict.items()}

    cvae.load_state_dict(state_dict)

cvae.eval()
bs_cvae, bs_ckpt = cvae, ckpt

In [7]:
print(f"bs checkpoint: {save_path}")
time_result = []
greek_key = ['delta', 'vega', 'rho', 'theta']
opt_key = ['van_call', 'van_put', 'barr_call', 'barr_put']
greek_result = {n: {m: [] for m in opt_key} for n in greek_key}

bs_eta = (1.0, 1.0, 0.03, np.sqrt(0.05), 1.5)
for i in range(30):
    start = time.time()
    result_bs = CVAE_greeks(
        bs_cvae,
        bs_ckpt,
        bs_eta,
        model_type=model_type,
        B=0.8,
        n_samples=100_000,
        #h={"delta": 0.01, "vega": 0.0004, "rho": 0.0003, "theta": 0.015},
        relative_step=0.01,
        antithetic=True,
        seed=1234 + i * 100,
        validate_samples=validate_samples,
        valid_resample=valid_resample,
        multiple=multiple,
    )
    time_result.append(time.time() - start)
    for key in greek_key:
        for opt in opt_key:
            greek_result[key][opt].append(result_bs["greeks"][key][opt])

print(f"Average time: {np.mean(time_result):.6f}s")
for key in greek_key:
    for opt in opt_key:
        print(f"Average {key} for {opt}: {np.mean(greek_result[key][opt]):.6f}")
    print("================================================================")

bs checkpoint: result/cvae/bs/cvae_bs_2_1024_16384_None_11-2e-05_12-2e-06_1_[15, 24, 78]_chunk1164.pt
Average time: 0.142441s
Average delta for van_call: 0.625881
Average delta for van_put: -0.374473
Average delta for barr_call: 0.678565
Average delta for barr_put: 0.015650
================================================================
Average vega for van_call: 0.452487
Average vega for van_put: 0.462999
Average vega for barr_call: 0.317164
Average vega for barr_put: -0.090706
================================================================
Average rho for van_call: 0.730127
Average rho for van_put: -0.693925
Average rho for barr_call: 0.713009
Average rho for barr_put: -0.037985
================================================================
Average theta for van_call: -0.048798
Average theta for van_put: -0.020761
Average theta for barr_call: -0.038218
Average theta for barr_put: 0.007859
================================================================

In [4]:
# hes
# CVAE training settings
model_type = 'hes' # hes_bbc
dim_z       = 2 # 2, 4, 8
hidden_dims = [1024,1024,1024,512] # [128, 128, 64], [512, 256, 128], [1024, 512, 256], [1024, 1024, 512, 256], [1024, 1024, 1024, 1024, 1024]
batch_size  = 16384 # 1024, 2048, 128-4096, 8192, 16384, 32768, 65536
bn_chunks   = None # None or num
use_bn      = True if bn_chunks is not None else False
lr          = 2e-5 # 수렴속도 1e-4 < 1e-5
l1          = 18
lr2         = 2e-6
l2          = 19
lr3         = 1e-6
l3          = 13
beta        = 1
validation_chunk_idxs = [15,24,78]
val_every_chunks = 97
memory_on_gpu = True
warmup_chunks = None # None or num
cvae_type = "base" # "base" or "barr_weight"(exponential), "normal_weight", "add_put_loss"
weight_mode = "barrier_put" # barr_weight : "barrier_put", "barrier_near" / normal_weight, add_put_loss: "barrier_put", "all_put"
weight_alpha = 0.0
weight_alpha2 = None
weight_h = 0.01 # 0.01, 0.03, 0.04
weight_normalize = True
resume_path = None # or None 이어서 학습하고 싶을 때

num_chunks  = 2037
multiple = 0  # 0이면 비활성화, 10이면 S_T >= 10*S0 폐기 후 재추출
nvp_multiple = 10
multiple_suffix = f"_multiple{multiple:g}" if multiple > 0 else ""

validate_samples = False
valid_resample = False
mt_corr = False
continuous_layer = 0
target_parameterization = "mt" # mt, ut

if cvae_type == "base":
    save_path   = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{batch_size}_{bn_chunks}_{lr}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}.pt"
    result_base_path = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{batch_size}_{bn_chunks}_{lr}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}"
    save_path   = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{batch_size}_{bn_chunks}_{l1}-{lr}_{l2}-{lr2}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}.pt"
    result_base_path = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{batch_size}_{bn_chunks}_{l1}-{lr}_{l2}-{lr2}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}"


if 'base' in save_path:
    raise ValueError("base는 save_path에 포함되면 안됨.")

n_samples = 10000 # n_samples= 1k, 10k, 100k
if n_samples % 2 != 0:
    raise ValueError("n_samples should be an even number for antithetic sampling")

if model_type == 'hes' or model_type == "hes_bbc":
    test_etas = [0.03, 2.0,  0.05, 0.5, -0.7, 0.05, 1.5]
    eta_keys  = ['r', 'lambda', 'v_bar', 'xi', 'rho', 'Y0', 'T']

if "ut" in save_path:
    ckpt = torch.load(save_path, map_location=device, weights_only=False)
    cvae = e_2_CVAE_UT.CVAE.from_checkpoint(ckpt).to(device)
else:
    ckpt = torch.load(save_path, map_location=device, weights_only=False)
    cvae = CVAE(
        dim_x=ckpt["dim_x"],
        dim_eta=ckpt["dim_eta"],
        dim_z=ckpt["dim_z"],
        hidden_dims=ckpt["hidden_dims"],
        use_bn=ckpt.get("use_bn", False),
        residual_blocks=ckpt.get("residual_blocks", 0),
    ).to(device)
    
    state_dict = ckpt["model_state"]
    if any(k.startswith("module.") for k in state_dict):
        state_dict = {k.replace("module.", "", 1): v for k, v in state_dict.items()}

    cvae.load_state_dict(state_dict)

cvae.eval()

eta_raw = np.array(test_etas, dtype=np.float32)
eta_scaled = (eta_raw - ckpt["eta_min"]) / (ckpt["eta_max"] - ckpt["eta_min"] + 1e-8)
eta_t = torch.tensor(eta_scaled, dtype=torch.float32, device=device)

hes_cvae, hes_ckpt = cvae, ckpt

In [ ]:
# hes_bbc
# CVAE training settings
model_type = 'hes_bbc' # hes_bbc
dim_z       = 3 # 2, 4, 8
hidden_dims = [1024,1024,1024,512] # [128, 128, 64], [512, 256, 128], [1024, 512, 256], [1024, 1024, 512, 256], [1024, 1024, 1024, 1024, 1024]
batch_size  = 16384 # 1024, 2048, 128-4096, 8192, 16384, 32768, 65536
bn_chunks   = None # None or num
use_bn      = True if bn_chunks is not None else False
lr          = 2e-5 # 수렴속도 1e-4 < 1e-5
l1          = 2
lr2         = 2e-6
l2          = 3
lr3         = 1e-6
l3          = 13
beta        = 1
validation_chunk_idxs = [15,24,78]
val_every_chunks = 97
memory_on_gpu = True
warmup_chunks = None # None or num
cvae_type = "base" # "base" or "barr_weight"(exponential), "normal_weight", "add_put_loss"
weight_mode = "barrier_put" # barr_weight : "barrier_put", "barrier_near" / normal_weight, add_put_loss: "barrier_put", "all_put"
weight_alpha = 0.0
weight_alpha2 = None
weight_h = 0.01 # 0.01, 0.03, 0.04
weight_normalize = True
resume_path = None # or None 이어서 학습하고 싶을 때

num_chunks  = 776
multiple = 0  # 0이면 비활성화, 10이면 S_T >= 10*S0 폐기 후 재추출
nvp_multiple = 10
multiple_suffix = f"_multiple{multiple:g}" if multiple > 0 else ""

validate_samples = False
valid_resample = False
mt_corr = False
continuous_layer = 0
target_parameterization = "mt" # mt, ut

if cvae_type == "base":
    save_path   = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{lr}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}.pt"
    result_base_path = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{lr}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}"
    save_path   = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{l1}-{lr}_{l2}-{lr2}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}.pt"
    result_base_path = f"result/cvae/{model_type}/cvae_{model_type}_{dim_z}_{hidden_dims[0]}\
_{l1}-{lr}_{l2}-{lr2}_{beta}_{validation_chunk_idxs}_chunk{num_chunks}"


if 'base' in save_path:
    raise ValueError("base는 save_path에 포함되면 안됨.")

n_samples = 10000 # n_samples= 1k, 10k, 100k
if n_samples % 2 != 0:
    raise ValueError("n_samples should be an even number for antithetic sampling")

if model_type == 'hes' or model_type == "hes_bbc":
    test_etas = [0.03, 2.0,  0.05, 0.5, -0.7, 0.05, 1.5]
    eta_keys  = ['r', 'lambda', 'v_bar', 'xi', 'rho', 'Y0', 'T']

if "ut" in save_path:
    ckpt = torch.load(save_path, map_location=device, weights_only=False)
    cvae = e_2_CVAE_UT.CVAE.from_checkpoint(ckpt).to(device)
else:
    ckpt = torch.load(save_path, map_location=device, weights_only=False)
    cvae = CVAE(
        dim_x=ckpt["dim_x"],
        dim_eta=ckpt["dim_eta"],
        dim_z=ckpt["dim_z"],
        hidden_dims=ckpt["hidden_dims"],
        use_bn=ckpt.get("use_bn", False),
        residual_blocks=ckpt.get("residual_blocks", 0),
    ).to(device)
    
    state_dict = ckpt["model_state"]
    if any(k.startswith("module.") for k in state_dict):
        state_dict = {k.replace("module.", "", 1): v for k, v in state_dict.items()}

    cvae.load_state_dict(state_dict)

cvae.eval()

eta_raw = np.array(test_etas, dtype=np.float32)
eta_scaled = (eta_raw - ckpt["eta_min"]) / (ckpt["eta_max"] - ckpt["eta_min"] + 1e-8)
eta_t = torch.tensor(eta_scaled, dtype=torch.float32, device=device)

hes_cvae, hes_ckpt = cvae, ckpt

In [9]:
# hes cvae
print(f"Heston checkpoint: {save_path}")
time_result = []
greek_key = ['delta', 'v0', 'rho', 'theta']
opt_key = ['van_call', 'van_put', 'barr_call', 'barr_put']
greek_result = {n: {m: [] for m in opt_key} for n in greek_key}

hes_eta = [1.0, 1.0, 0.03, 2.0, 0.05, 0.5, -0.7, 0.04, 1.5]
for i in range(30):
    start = time.time()
    result_hes = CVAE_greeks(
        hes_cvae,
        hes_ckpt,
        hes_eta,
        model_type=model_type,
        B=0.8,
        n_samples=100_000,
        #h={"delta": 0.01, "v0": 0.0004, "rho": 0.0003, "theta": 0.015},
        relative_step=0.01,
        antithetic=True,
        seed=1234 + i * 100,
        validate_samples=validate_samples,
        valid_resample=valid_resample,
        multiple=multiple,
    )
    time_result.append(time.time() - start)
    for key in greek_key:
        for opt in opt_key:
            greek_result[key][opt].append(result_hes["greeks"][key][opt])

print(f"Average time: {np.mean(time_result):.6f}s")
for key in greek_key:
    for opt in opt_key:
        print(f"Average {key} for {opt}: {np.mean(greek_result[key][opt]):.6f}")
    print("================================================================")

Heston checkpoint: result/cvae/hes/cvae_hes_2_1024_16384_None_18-2e-05_19-2e-06_1_[15, 24, 78]_chunk2037.pt
Average time: 0.133273s
Average delta for van_call: 0.701911
Average delta for van_put: -0.297310
Average delta for barr_call: 0.727536
Average delta for barr_put: -0.009224
================================================================
Average v0 for van_call: 0.324126
Average v0 for van_put: 0.318590
Average v0 for barr_call: 0.236395
Average v0 for barr_put: -0.033490
================================================================
Average rho for van_call: 0.846456
Average rho for van_put: -0.572302
Average rho for barr_call: 0.801866
Average rho for barr_put: -0.050457
================================================================
Average theta for van_call: -0.049415
Average theta for van_put: -0.020879
Average theta for barr_call: -0.040195
Average theta for barr_put: 0.004554
================================================================

# AD

In [6]:
from e_3_CVAE_greek_AD import CVAE_greeks_AD

In [9]:
# bs cvae AD
print(f"save_path: {save_path}")
time_result = []
greek_key = ['delta', 'vega', 'rho', 'theta']
opt_key = ['van_call', 'van_put', 'barr_call', 'barr_put']
greek_result = {n: {m: [] for m in opt_key} for n in greek_key}

bs_eta = (1.0, 1.0, 0.03, np.sqrt(0.05), 1.5)
for i in range(50):
    start = time.time()
    result_bs = CVAE_greeks_AD(
        bs_cvae,
        bs_ckpt,
        bs_eta,
        model_type="bs",
        B=0.8,
        greeks=("delta", "vega", "rho", "theta"),
        n_samples=100_000,
        antithetic=True,
        seed=1234,
    )
    time_result.append(time.time() - start)
    for key in greek_key:
        for opt in opt_key:
            greek_result[key][opt].append(result_bs["greeks"][key][opt])

print(f"Average time: {np.mean(time_result):.6f}s")
for key in greek_key:
    for opt in opt_key:
        print(f"Average {key} for {opt}: {np.mean(greek_result[key][opt]):.6f}")
    print("================================================================")

save_path: result/cvae/bs/cvae_bs_2_1024_16384_None_11-2e-05_12-2e-06_1_[15, 24, 78]_chunk1164.pt

/home/enjongoopee/miniconda3/envs/env_paper/lib/python3.13/site-packages/torch/utils/_contextlib.py:124: RuntimeWarning: Hard-indicator AD is a frozen-indicator diagnostic and ignores the derivative of barrier survival; it is not the full barrier Greek.
  return func(*args, **kwargs)

Average time: 0.207269s
Average delta for van_call: 0.619187
Average delta for van_put: -0.381117
Average delta for barr_call: 0.564614
Average delta for barr_put: -0.121702
================================================================
Average vega for van_call: 0.453547
Average vega for van_put: 0.462567
Average vega for barr_call: 0.437421
Average vega for barr_put: 0.088775
================================================================
Average rho for van_call: 0.730736
Average rho for van_put: -0.694452
Average rho for barr_call: 0.661678
Average rho for barr_put: -0.192764
================================================================
Average theta for van_call: -0.048900
Average theta for van_put: -0.020858
Average theta for barr_call: -0.046260
Average theta for barr_put: -0.002897
================================================================

In [ ]:
# hes
time_result = []
greek_key = ["delta", "v0", "rho", "theta"]
opt_key = ["van_call", "van_put", "barr_call", "barr_put"]
greek_result = {greek: {option: [] for option in opt_key} for greek in greek_key}

hes_eta = (1.0, 1.0, 0.03, 2.0, 0.05, 0.5, -0.7, 0.04, 1.5)
for i in range(30):
    start = time.time()
    result_hes = CVAE_greeks_AD(
        hes_cvae,
        hes_ckpt,
        hes_eta,
        model_type="hes",
        B=0.8,
        greeks=("delta", "rho", "v0", "theta"),
        n_samples=100_000,
        antithetic=True,
        seed=1234,
    )
    time_result.append(time.time() - start)
    for greek in greek_key:
        for option in opt_key:
            greek_result[greek][option].append(result_hes["greeks"][greek][option])

print(f"Average time: {np.mean(time_result):.6f}s")
for greek in greek_key:
    for option in opt_key:
        print(f"Average {greek} for {option}: {np.mean(greek_result[greek][option]):.6f}")
    print("================================================================")

Average time: 0.199272s
Average delta for van_call: 0.694763
Average delta for van_put: -0.304375
Average delta for barr_call: 0.626840
Average delta for barr_put: -0.084736
================================================================
Average v0 for van_call: 0.325603
Average v0 for van_put: 0.318974
Average v0 for barr_call: 0.315002
Average v0 for barr_put: 0.050797
================================================================
Average rho for van_call: 0.845623
Average rho for van_put: -0.573552
Average rho for barr_call: 0.757775
Average rho for barr_put: -0.130939
================================================================
Average theta for van_call: -0.049617
Average theta for van_put: -0.020998
Average theta for barr_call: -0.046635
Average theta for barr_put: -0.002218
================================================================

# MAE

In [5]:
MC_DT = 0.001
bs_para = generate_BS_params(n_sets=100, seed=1234)
bs_para[:, 2] = np.round(bs_para[:, 2] / MC_DT) * MC_DT

In [6]:
import numpy as np

from e_0_generate import generate_BS_params

MC_DT = 0.001


def generate_valid_bs_params(n_sets=100, seed=1234):
    """두 조건을 모두 만족하는 [r, sigma, T]를 정확히 n_sets개 생성합니다."""
    accepted_batches = []
    n_accepted = 0
    batch_index = 0

    while n_accepted < n_sets:
        batch_size = max(256, 2 * (n_sets - n_accepted))
        candidates = generate_BS_params(
            n_sets=batch_size,
            seed=seed if batch_index == 0 else None,
        )

        # 후속 MC 계산에서 사용하는 최종 T 값으로 먼저 맞춥니다.
        candidates[:, 2] = np.round(candidates[:, 2] / MC_DT) * MC_DT
        r = candidates[:, 0]
        sigma = candidates[:, 1]
        T = candidates[:, 2]

        valid = (np.abs(r - sigma**2 / 2) <= 0.3) & (sigma**2 <= T)
        accepted = candidates[valid]
        if len(accepted):
            accepted_batches.append(accepted)
            n_accepted += len(accepted)
        batch_index += 1

    return np.vstack(accepted_batches)[:n_sets]


# 다음 BS MAE 셀이 그대로 사용할 변수명입니다.
bs_para = generate_valid_bs_params(n_sets=100, seed=1234)

bs_r, bs_sigma, bs_T = bs_para.T
bs_abs_condition = np.abs(bs_r - bs_sigma**2 / 2) <= 0.3
bs_variance_condition = bs_sigma**2 <= bs_T

assert bs_para.shape == (100, 3)
assert np.all(bs_abs_condition & bs_variance_condition)
print(f"생성된 BS eta: {len(bs_para)}개")
print(f"|r - sigma^2 / 2| <= 0.3: {bs_abs_condition.sum()}/100")
print(f"sigma^2 <= T: {bs_variance_condition.sum()}/100")

생성된 BS eta: 100개
|r - sigma^2 / 2| <= 0.3: 100/100
sigma^2 <= T: 100/100

In [25]:
# BS delta MAE/MSE: closed-form is the reference. 90m
import time
import pandas as pd

MC_REPEATS = 30
CVAE_REPEATS = 30
REPEAT_SEED_STRIDE = 10_000

OPTION_SPECS = {
    "van_call": ("call", None),
    "van_put": ("put", None),
    "barr_call": ("call", 0.8),
    "barr_put": ("put", 0.8),
}

ratio = 0.01
n_samples = 100_000
bs_delta_rows = []
cell_started_at = time.perf_counter()
print(f"BS MAE cell started: {time.strftime('%H:%M:%S')}", flush=True)

for row_idx, (r, sigma, T) in enumerate(bs_para):
    eta_started_at = time.perf_counter()
    T = round(float(T) / 0.001) * 0.001
    eta = (1.0, 1.0, float(r), float(sigma), T)
    print(
        f"[eta {row_idx + 1}/{len(bs_para)}] started: "
        f"{time.strftime('%H:%M:%S')} | eta={eta}",
        flush=True,
    )
    bs_greek_h = {
        "delta": max(abs(eta[0]) * ratio, 1e-6),
        "vega": max(abs(eta[3]) * ratio, 1e-6),
        "rho": max(abs(eta[2]) * ratio, 1e-6),
        "theta": max(abs(eta[4]) * ratio, 1e-6),
    }
    seed = 1234 + row_idx * 100

    closed_delta = {
        option: BS_greeks(eta, type=opt_type, B=B, h=bs_greek_h)["delta"]
        for option, (opt_type, B) in OPTION_SPECS.items()
    }

    mc_values = {option: [] for option in OPTION_SPECS}
    mc_started_at = time.perf_counter()
    print(
        f"[eta {row_idx + 1}] MC started: {time.strftime('%H:%M:%S')} "
        f"({MC_REPEATS} repeats x {len(OPTION_SPECS)} options)",
        flush=True,
    )
    for repeat_idx in range(MC_REPEATS):
        repeat_seed = seed + repeat_idx * REPEAT_SEED_STRIDE
        for option, (opt_type, B) in OPTION_SPECS.items():
            mc_result = MC_BS_greeks_gpu(
                eta,
                B=B,
                opt_type=opt_type,
                greeks=("delta",),
                n_paths=n_samples,
                dt=0.001,
                h=bs_greek_h,
                seed=repeat_seed,
                antithetic=True,
            )
            mc_values[option].append(mc_result["delta"])
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    mc_elapsed = time.perf_counter() - mc_started_at
    print(
        f"[eta {row_idx + 1}] MC finished: {time.strftime('%H:%M:%S')} "
        f"| elapsed={mc_elapsed:.3f}s",
        flush=True,
    )

    cvae_values = {option: [] for option in OPTION_SPECS}
    cvae_started_at = time.perf_counter()
    print(
        f"[eta {row_idx + 1}] CVAE started: {time.strftime('%H:%M:%S')} "
        f"({CVAE_REPEATS} repeats)",
        flush=True,
    )
    for repeat_idx in range(CVAE_REPEATS):
        repeat_seed = seed + repeat_idx * REPEAT_SEED_STRIDE
        cvae_result = CVAE_greeks(
            bs_cvae,
            bs_ckpt,
            eta,
            model_type="bs",
            B=0.8,
            greeks=("delta",),
            n_samples=n_samples,
            h=bs_greek_h,
            antithetic=True,
            seed=repeat_seed,
        )
        for option in OPTION_SPECS:
            cvae_values[option].append(cvae_result["greeks"]["delta"][option])
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    cvae_elapsed = time.perf_counter() - cvae_started_at
    print(
        f"[eta {row_idx + 1}] CVAE finished: {time.strftime('%H:%M:%S')} "
        f"| elapsed={cvae_elapsed:.3f}s",
        flush=True,
    )

    mc_delta = {
        option: float(np.mean(values))
        for option, values in mc_values.items()
    }
    cvae_delta = {
        option: float(np.mean(values))
        for option, values in cvae_values.items()
    }

    for option in OPTION_SPECS:
        bs_delta_rows.append(
            {
                "set_idx": row_idx,
                "option": option,
                "opt_type": OPTION_SPECS[option][0],
                "barrier": OPTION_SPECS[option][1],
                "S0": eta[0],
                "K": eta[1],
                "r": eta[2],
                "sigma": eta[3],
                "T": eta[4],
                "closed_form_delta": closed_delta[option],
                "mc_100k_delta": mc_delta[option],
                "cvae_100k_delta": cvae_delta[option],
                "mc_100k_n_paths": n_samples,
                "mc_dt": 0.001,
                "mc_seed": seed,
                "cvae_100k_n_samples": n_samples,
                "cvae_seed": seed,
                "mc_repeat_count": MC_REPEATS,
                "cvae_repeat_count": CVAE_REPEATS,
                "repeat_seed_stride": REPEAT_SEED_STRIDE,
                "delta_h": bs_greek_h["delta"],
                "rho_h": bs_greek_h["rho"],
                "vega_h": bs_greek_h["vega"],
                "theta_h": bs_greek_h["theta"],
            }
        )

    eta_elapsed = time.perf_counter() - eta_started_at
    print(
        f"[eta {row_idx + 1}/{len(bs_para)}] finished: "
        f"{time.strftime('%H:%M:%S')} | elapsed={eta_elapsed:.3f}s | "
        f"total_elapsed={time.perf_counter() - cell_started_at:.3f}s",
        flush=True,
    )

print(
    f"BS MAE cell finished: {time.strftime('%H:%M:%S')} | "
    f"elapsed={time.perf_counter() - cell_started_at:.3f}s",
    flush=True,
)

BS MAE cell started: 01:41:47
[eta 1/100] started: 01:41:47 | eta=(1.0, 1.0, 0.01915194503788923, 0.18408308304328516, 0.591)
[eta 1] MC started: 01:41:47 (30 repeats x 4 options)
[eta 1] MC finished: 01:42:09 | elapsed=22.375s
[eta 1] CVAE started: 01:42:09 (30 repeats)
[eta 1] CVAE finished: 01:42:10 | elapsed=0.997s
[eta 1/100] finished: 01:42:10 | elapsed=23.392s | total_elapsed=23.394s
[eta 2/100] started: 01:42:10 | eta=(1.0, 1.0, 0.07853585837137693, 0.5560977310652871, 0.803)
[eta 2] MC started: 01:42:10 (30 repeats x 4 options)
[eta 2] MC finished: 01:42:33 | elapsed=23.370s
[eta 2] CVAE started: 01:42:33 (30 repeats)
[eta 2] CVAE finished: 01:42:34 | elapsed=1.036s
[eta 2/100] finished: 01:42:34 | elapsed=24.415s | total_elapsed=47.809s
[eta 3/100] started: 01:42:34 | eta=(1.0, 1.0, 0.07799758081188035, 0.6298620530777619, 0.427)
[eta 3] MC started: 01:42:34 (30 repeats x 4 options)
[eta 3] MC finished: 01:42:47 | elapsed=12.835s
[eta 3] CVAE started: 01:42:47 (30 repeats)
[eta 3] CVAE finished: 01:42:48 | elapsed=1.044s
[eta 3/100] finished: 01:42:48 | elapsed=13.888s | total_elapsed=61.698s
[eta 4/100] started: 01:42:48 | eta=(1.0, 1.0, 0.027259260528264162, 0.686493895255771, 1.274)
[eta 4] MC started: 01:42:48 (30 repeats x 4 options)
[eta 4] MC finished: 01:43:26 | elapsed=37.474s
[eta 4] CVAE started: 01:43:26 (30 repeats)
[eta 4] CVAE finished: 01:43:27 | elapsed=0.993s
[eta 4/100] finished: 01:43:27 | elapsed=38.479s | total_elapsed=100.179s
[eta 5/100] started: 01:43:27 | eta=(1.0, 1.0, 0.02764642551430967, 0.2411421549852638, 0.222)
[eta 5] MC started: 01:43:27 (30 repeats x 4 options)
[eta 5] MC finished: 01:43:34 | elapsed=6.751s
[eta 5] CVAE started: 01:43:34 (30 repeats)
[eta 5] CVAE finished: 01:43:35 | elapsed=1.063s
[eta 5/100] finished: 01:43:35 | elapsed=7.821s | total_elapsed=108.000s
[eta 6/100] started: 01:43:35 | eta=(1.0, 1.0, 0.08018721775350193, 0.7881398601915601, 2.787)
[eta 6] MC started: 01:43:35 (30 repeats x 4 options)
[eta 6] MC finished: 01:44:57 | elapsed=82.126s
[eta 6] CVAE started: 01:44:57 (30 repeats)
[eta 6] CVAE finished: 01:44:58 | elapsed=1.029s
[eta 6/100] finished: 01:44:58 | elapsed=83.164s | total_elapsed=191.165s
[eta 7/100] started: 01:44:58 | eta=(1.0, 1.0, 0.09581393536837052, 0.8566209796025113, 2.8120000000000003)
[eta 7] MC started: 01:44:58 (30 repeats x 4 options)
[eta 7] MC finished: 01:46:21 | elapsed=83.540s
[eta 7] CVAE started: 01:46:21 (30 repeats)
[eta 7] CVAE finished: 01:46:22 | elapsed=1.052s
[eta 7/100] finished: 01:46:22 | elapsed=84.604s | total_elapsed=275.770s
[eta 8/100] started: 01:46:22 | eta=(1.0, 1.0, 0.08759326347420948, 0.7280682195830206, 2.45)
[eta 8] MC started: 01:46:22 (30 repeats x 4 options)
[eta 8] MC finished: 01:47:35 | elapsed=72.940s
[eta 8] CVAE started: 01:47:35 (30 repeats)
[eta 8] CVAE finished: 01:47:36 | elapsed=1.108s
[eta 8/100] finished: 01:47:36 | elapsed=74.054s | total_elapsed=349.825s
[eta 9/100] started: 01:47:36 | eta=(1.0, 1.0, 0.03578172699578667, 0.6926527982725451, 0.646)
[eta 9] MC started: 01:47:37 (30 repeats x 4 options)
[eta 9] MC finished: 01:47:56 | elapsed=19.562s
[eta 9] CVAE started: 01:47:56 (30 repeats)
[eta 9] CVAE finished: 01:47:57 | elapsed=1.101s
[eta 9/100] finished: 01:47:57 | elapsed=20.672s | total_elapsed=370.497s
[eta 10/100] started: 01:47:57 | eta=(1.0, 1.0, 0.050099512552345876, 0.4728785881311146, 1.803)
[eta 10] MC started: 01:47:57 (30 repeats x 4 options)
[eta 10] MC finished: 01:48:51 | elapsed=53.601s
[eta 10] CVAE started: 01:48:51 (30 repeats)
[eta 10] CVAE finished: 01:48:52 | elapsed=1.027s
[eta 10/100] finished: 01:48:52 | elapsed=54.635s | total_elapsed=425.133s
[eta 11/100] started: 01:48:52 | eta=(1.0, 1.0, 0.06834629351721364, 0.8570160689925663, 2.72)
[eta 11] MC started: 01:48:52 (30 repeats x 4 options)
[eta 11] MC finished: 01:50:11 | elapsed=79.181s
[eta 11] CVAE started: 01:50:11 (30 repeats)
[eta 11] CVAE finished: 01:50:12 | elapsed=1.014s
[eta 11/100] finished: 01:50:12 | elapsed=80.206s | total_elapsed=505.340s
[eta 12/100] started: 01:50:12 | eta=(1.0, 1.0, 0.07127020269829003, 0.6650785905704018, 2.9050000000000002)
[eta 12] MC started: 01:50:12 (30 repeats x 4 options)
[eta 12] MC finished: 01:51:36 | elapsed=84.359s
[eta 12] CVAE started: 01:51:36 (30 repeats)
[eta 12] CVAE finished: 01:51:37 | elapsed=1.015s
[eta 12/100] finished: 01:51:37 | elapsed=85.384s | total_elapsed=590.724s
[eta 13/100] started: 01:51:37 | eta=(1.0, 1.0, 0.03702507547903949, 0.3340425663330492, 0.296)
[eta 13] MC started: 01:51:37 (30 repeats x 4 options)
[eta 13] MC finished: 01:51:46 | elapsed=8.722s
[eta 13] CVAE started: 01:51:46 (30 repeats)
[eta 13] CVAE finished: 01:51:47 | elapsed=1.054s
[eta 13/100] finished: 01:51:47 | elapsed=9.786s | total_elapsed=600.510s
[eta 14/100] started: 01:51:47 | eta=(1.0, 1.0, 0.0561196186065625, 0.5186273537570569, 1.0210000000000001)
[eta 14] MC started: 01:51:47 (30 repeats x 4 options)
[eta 14] MC finished: 01:52:17 | elapsed=29.789s
[eta 14] CVAE started: 01:52:17 (30 repeats)
[eta 14] CVAE finished: 01:52:18 | elapsed=1.032s
[eta 14/100] finished: 01:52:18 | elapsed=30.832s | total_elapsed=631.342s
[eta 15/100] started: 01:52:18 | eta=(1.0, 1.0, 0.050308316530780973, 0.3952938948617274, 2.121)
[eta 15] MC started: 01:52:18 (30 repeats x 4 options)
[eta 15] MC finished: 01:53:20 | elapsed=62.092s
[eta 15] CVAE started: 01:53:20 (30 repeats)
[eta 15] CVAE finished: 01:53:21 | elapsed=1.010s
[eta 15/100] finished: 01:53:21 | elapsed=63.110s | total_elapsed=694.453s
[eta 16/100] started: 01:53:21 | eta=(1.0, 1.0, 0.0013768449590682243, 0.03201854875800498, 1.957)
[eta 16] MC started: 01:53:21 (30 repeats x 4 options)
[eta 16] MC finished: 01:54:19 | elapsed=57.766s
[eta 16] CVAE started: 01:54:19 (30 repeats)
[eta 16] CVAE finished: 01:54:20 | elapsed=1.088s
[eta 16/100] finished: 01:54:20 | elapsed=58.864s | total_elapsed=753.318s
[eta 17/100] started: 01:54:20 | eta=(1.0, 1.0, 0.07728266216123741, 0.5772630032899877, 1.935)
[eta 17] MC started: 01:54:20 (30 repeats x 4 options)
[eta 17] MC finished: 01:55:17 | elapsed=57.018s
[eta 17] CVAE started: 01:55:17 (30 repeats)
[eta 17] CVAE finished: 01:55:18 | elapsed=1.014s
[eta 17/100] finished: 01:55:18 | elapsed=58.044s | total_elapsed=811.363s
[eta 18/100] started: 01:55:18 | eta=(1.0, 1.0, 0.08826411906361166, 0.850401493603512, 2.503)
[eta 18] MC started: 01:55:18 (30 repeats x 4 options)
[eta 18] MC finished: 01:56:32 | elapsed=73.834s
[eta 18] CVAE started: 01:56:32 (30 repeats)
[eta 18] CVAE finished: 01:56:33 | elapsed=1.037s
[eta 18/100] finished: 01:56:33 | elapsed=74.883s | total_elapsed=886.247s
[eta 19/100] started: 01:56:33 | eta=(1.0, 1.0, 0.061539617843349374, 0.6832958183111585, 1.073)
[eta 19] MC started: 01:56:33 (30 repeats x 4 options)
[eta 19] MC finished: 01:57:04 | elapsed=31.436s
[eta 19] CVAE started: 01:57:04 (30 repeats)
[eta 19] CVAE finished: 01:57:05 | elapsed=1.043s
[eta 19/100] finished: 01:57:05 | elapsed=32.490s | total_elapsed=918.737s
[eta 20/100] started: 01:57:05 | eta=(1.0, 1.0, 0.0075381241642976556, 0.07708638564783193, 0.586)
[eta 20] MC started: 01:57:05 (30 repeats x 4 options)
[eta 20] MC finished: 01:57:23 | elapsed=17.241s
[eta 20] CVAE started: 01:57:23 (30 repeats)
[eta 20] CVAE finished: 01:57:24 | elapsed=1.102s
[eta 20/100] finished: 01:57:24 | elapsed=18.351s | total_elapsed=937.089s
[eta 21/100] started: 01:57:24 | eta=(1.0, 1.0, 0.03688240060019745, 0.4106678648297145, 2.318)
[eta 21] MC started: 01:57:24 (30 repeats x 4 options)
[eta 21] MC finished: 01:58:30 | elapsed=65.985s
[eta 21] CVAE started: 01:58:30 (30 repeats)
[eta 21] CVAE finished: 01:58:31 | elapsed=1.021s
[eta 21/100] finished: 01:58:31 | elapsed=67.015s | total_elapsed=1004.105s
[eta 22/100] started: 01:58:31 | eta=(1.0, 1.0, 0.09331401019825217, 0.042859497372964975, 1.1420000000000001)
[eta 22] MC started: 01:58:31 (30 repeats x 4 options)
[eta 22] MC finished: 01:59:04 | elapsed=33.045s
[eta 22] CVAE started: 01:59:04 (30 repeats)
[eta 22] CVAE finished: 01:59:05 | elapsed=1.090s
[eta 22/100] finished: 01:59:05 | elapsed=34.145s | total_elapsed=1038.250s
[eta 23/100] started: 01:59:05 | eta=(1.0, 1.0, 0.06513781432265774, 0.1750126447438038, 0.355)
[eta 23] MC started: 01:59:05 (30 repeats x 4 options)
[eta 23] MC finished: 01:59:15 | elapsed=10.566s
[eta 23] CVAE started: 01:59:15 (30 repeats)
[eta 23] CVAE finished: 01:59:17 | elapsed=1.020s
[eta 23/100] finished: 01:59:17 | elapsed=11.594s | total_elapsed=1049.844s
[eta 24/100] started: 01:59:17 | eta=(1.0, 1.0, 0.039720257772615425, 0.5658366035591887, 2.216)
[eta 24] MC started: 01:59:17 (30 repeats x 4 options)
[eta 24] MC finished: 02:00:21 | elapsed=64.919s
[eta 24] CVAE started: 02:00:21 (30 repeats)
[eta 24] CVAE finished: 02:00:22 | elapsed=1.043s
[eta 24/100] finished: 02:00:22 | elapsed=65.969s | total_elapsed=1115.813s
[eta 25/100] started: 02:00:22 | eta=(1.0, 1.0, 0.07887301429407456, 0.17371827942926052, 2.6550000000000002)
[eta 25] MC started: 02:00:22 (30 repeats x 4 options)
[eta 25] MC finished: 02:01:40 | elapsed=78.007s
[eta 25] CVAE started: 02:01:40 (30 repeats)
[eta 25] CVAE finished: 02:01:42 | elapsed=1.057s
[eta 25/100] finished: 02:01:42 | elapsed=79.072s | total_elapsed=1194.886s
[eta 26/100] started: 02:01:42 | eta=(1.0, 1.0, 0.05680986526260692, 0.5144902486965915, 0.607)
[eta 26] MC started: 02:01:42 (30 repeats x 4 options)
[eta 26] MC finished: 02:02:00 | elapsed=18.161s
[eta 26] CVAE started: 02:02:00 (30 repeats)
[eta 26] CVAE finished: 02:02:01 | elapsed=1.016s
[eta 26/100] finished: 02:02:01 | elapsed=19.185s | total_elapsed=1214.072s
[eta 27/100] started: 02:02:01 | eta=(1.0, 1.0, 0.08691273895612259, 0.8690020166598295, 1.318)
[eta 27] MC started: 02:02:01 (30 repeats x 4 options)
[eta 27] MC finished: 02:02:40 | elapsed=38.962s
[eta 27] CVAE started: 02:02:40 (30 repeats)
[eta 27] CVAE finished: 02:02:41 | elapsed=1.023s
[eta 27/100] finished: 02:02:41 | elapsed=39.993s | total_elapsed=1254.065s
[eta 28/100] started: 02:02:41 | eta=(1.0, 1.0, 0.04361734238956794, 0.7206269006830219, 1.088)
[eta 28] MC started: 02:02:41 (30 repeats x 4 options)
[eta 28] MC finished: 02:03:13 | elapsed=32.206s
[eta 28] CVAE started: 02:03:13 (30 repeats)
[eta 28] CVAE finished: 02:03:14 | elapsed=1.054s
[eta 28/100] finished: 02:03:14 | elapsed=33.269s | total_elapsed=1287.335s
[eta 29/100] started: 02:03:14 | eta=(1.0, 1.0, 0.014376682451456457, 0.27833738323513874, 0.427)
[eta 29] MC started: 02:03:14 (30 repeats x 4 options)
[eta 29] MC finished: 02:03:27 | elapsed=12.857s
[eta 29] CVAE started: 02:03:27 (30 repeats)
[eta 29] CVAE finished: 02:03:28 | elapsed=1.019s
[eta 29/100] finished: 02:03:28 | elapsed=13.884s | total_elapsed=1301.219s
[eta 30/100] started: 02:03:28 | eta=(1.0, 1.0, 0.07042609711183355, 0.25740876674930646, 1.37)
[eta 30] MC started: 02:03:28 (30 repeats x 4 options)
[eta 30] MC finished: 02:04:09 | elapsed=40.900s
[eta 30] CVAE started: 02:04:09 (30 repeats)
[eta 30] CVAE finished: 02:04:10 | elapsed=1.045s
[eta 30/100] finished: 02:04:10 | elapsed=41.950s | total_elapsed=1343.170s
[eta 31/100] started: 02:04:10 | eta=(1.0, 1.0, 0.04421407554041767, 0.6412718996138187, 0.48)
[eta 31] MC started: 02:04:10 (30 repeats x 4 options)
[eta 31] MC finished: 02:04:24 | elapsed=14.358s
[eta 31] CVAE started: 02:04:24 (30 repeats)
[eta 31] CVAE finished: 02:04:25 | elapsed=0.988s
[eta 31/100] finished: 02:04:25 | elapsed=15.355s | total_elapsed=1358.525s
[eta 32/100] started: 02:04:25 | eta=(1.0, 1.0, 0.09093159589724725, 0.3306773811466757, 0.66)
[eta 32] MC started: 02:04:25 (30 repeats x 4 options)
[eta 32] MC finished: 02:04:45 | elapsed=19.513s
[eta 32] CVAE started: 02:04:45 (30 repeats)
[eta 32] CVAE finished: 02:04:46 | elapsed=1.092s
[eta 32/100] finished: 02:04:46 | elapsed=20.614s | total_elapsed=1379.140s
[eta 33/100] started: 02:04:46 | eta=(1.0, 1.0, 0.00598092227798519, 0.607068541012931, 1.369)
[eta 33] MC started: 02:04:46 (30 repeats x 4 options)
[eta 33] MC finished: 02:05:26 | elapsed=39.799s
[eta 33] CVAE started: 02:05:26 (30 repeats)
[eta 33] CVAE finished: 02:05:27 | elapsed=1.003s
[eta 33/100] finished: 02:05:27 | elapsed=40.807s | total_elapsed=1419.948s
[eta 34/100] started: 02:05:27 | eta=(1.0, 1.0, 0.004735527880151514, 0.6283371003957005, 2.344)
[eta 34] MC started: 02:05:27 (30 repeats x 4 options)
[eta 34] MC finished: 02:06:34 | elapsed=67.494s
[eta 34] CVAE started: 02:06:34 (30 repeats)
[eta 34] CVAE finished: 02:06:35 | elapsed=1.023s
[eta 34/100] finished: 02:06:35 | elapsed=68.522s | total_elapsed=1488.471s
[eta 35/100] started: 02:06:35 | eta=(1.0, 1.0, 0.06748809435823303, 0.1188051344432096, 0.482)
[eta 35] MC started: 02:06:35 (30 repeats x 4 options)
[eta 35] MC finished: 02:06:49 | elapsed=14.142s
[eta 35] CVAE started: 02:06:49 (30 repeats)
[eta 35] CVAE finished: 02:06:50 | elapsed=0.993s
[eta 35/100] finished: 02:06:50 | elapsed=15.144s | total_elapsed=1503.615s
[eta 36/100] started: 02:06:50 | eta=(1.0, 1.0, 0.05946247799344489, 0.2865917956778052, 2.789)
[eta 36] MC started: 02:06:50 (30 repeats x 4 options)
[eta 36] MC finished: 02:08:12 | elapsed=81.461s
[eta 36] CVAE started: 02:08:12 (30 repeats)
[eta 36] CVAE finished: 02:08:13 | elapsed=1.038s
[eta 36/100] finished: 02:08:13 | elapsed=82.507s | total_elapsed=1586.123s
[eta 37/100] started: 02:08:13 | eta=(1.0, 1.0, 0.004332406269480349, 0.43236904764243345, 1.239)
[eta 37] MC started: 02:08:13 (30 repeats x 4 options)
[eta 37] MC finished: 02:08:50 | elapsed=36.709s
[eta 37] CVAE started: 02:08:50 (30 repeats)
[eta 37] CVAE finished: 02:08:51 | elapsed=1.015s
[eta 37/100] finished: 02:08:51 | elapsed=37.733s | total_elapsed=1623.856s
[eta 38/100] started: 02:08:51 | eta=(1.0, 1.0, 0.05614330800633979, 0.5746601793692814, 0.508)
[eta 38] MC started: 02:08:51 (30 repeats x 4 options)
[eta 38] MC finished: 02:09:06 | elapsed=15.068s
[eta 38] CVAE started: 02:09:06 (30 repeats)
[eta 38] CVAE finished: 02:09:07 | elapsed=1.051s
[eta 38/100] finished: 02:09:07 | elapsed=16.129s | total_elapsed=1639.987s
[eta 39/100] started: 02:09:07 | eta=(1.0, 1.0, 0.05029668331126184, 0.1984553963281352, 0.369)
[eta 39] MC started: 02:09:07 (30 repeats x 4 options)
[eta 39] MC finished: 02:09:18 | elapsed=11.112s
[eta 39] CVAE started: 02:09:18 (30 repeats)
[eta 39] CVAE finished: 02:09:19 | elapsed=1.014s
[eta 39/100] finished: 02:09:19 | elapsed=12.134s | total_elapsed=1652.121s
[eta 40/100] started: 02:09:19 | eta=(1.0, 1.0, 0.011189431757440383, 0.1665427237926093, 2.672)
[eta 40] MC started: 02:09:19 (30 repeats x 4 options)
[eta 40] MC finished: 02:10:38 | elapsed=79.183s
[eta 40] CVAE started: 02:10:38 (30 repeats)
[eta 40] CVAE finished: 02:10:39 | elapsed=1.060s
[eta 40/100] finished: 02:10:39 | elapsed=80.250s | total_elapsed=1732.372s
[eta 41/100] started: 02:10:39 | eta=(1.0, 1.0, 0.060719370621848456, 0.5014894674642764, 0.588)
[eta 41] MC started: 02:10:39 (30 repeats x 4 options)
[eta 41] MC finished: 02:10:57 | elapsed=17.704s
[eta 41] CVAE started: 02:10:57 (30 repeats)
[eta 41] CVAE finished: 02:10:58 | elapsed=1.049s
[eta 41/100] finished: 02:10:58 | elapsed=18.761s | total_elapsed=1751.133s
[eta 42/100] started: 02:10:58 | eta=(1.0, 1.0, 0.000676406199000279, 0.39459781949733813, 1.997)
[eta 42] MC started: 02:10:58 (30 repeats x 4 options)
[eta 42] MC finished: 02:11:57 | elapsed=59.646s
[eta 42] CVAE started: 02:11:57 (30 repeats)
[eta 42] CVAE finished: 02:11:58 | elapsed=1.025s
[eta 42/100] finished: 02:11:58 | elapsed=60.678s | total_elapsed=1811.811s
[eta 43/100] started: 02:11:58 | eta=(1.0, 1.0, 0.06174417088042971, 0.7142992520113383, 1.854)
[eta 43] MC started: 02:11:58 (30 repeats x 4 options)
[eta 43] MC finished: 02:12:53 | elapsed=54.936s
[eta 43] CVAE started: 02:12:53 (30 repeats)
[eta 43] CVAE finished: 02:12:54 | elapsed=1.021s
[eta 43/100] finished: 02:12:54 | elapsed=55.966s | total_elapsed=1867.778s
[eta 44/100] started: 02:12:54 | eta=(1.0, 1.0, 0.09121228864331543, 0.1767283651538495, 1.245)
[eta 44] MC started: 02:12:54 (30 repeats x 4 options)
[eta 44] MC finished: 02:13:31 | elapsed=36.417s
[eta 44] CVAE started: 02:13:31 (30 repeats)
[eta 44] CVAE finished: 02:13:32 | elapsed=1.079s
[eta 44/100] finished: 02:13:32 | elapsed=37.509s | total_elapsed=1905.288s
[eta 45/100] started: 02:13:32 | eta=(1.0, 1.0, 0.07905241330570334, 0.07162548257169221, 1.186)
[eta 45] MC started: 02:13:32 (30 repeats x 4 options)
[eta 45] MC finished: 02:14:06 | elapsed=34.139s
[eta 45] CVAE started: 02:14:06 (30 repeats)
[eta 45] CVAE finished: 02:14:07 | elapsed=1.021s
[eta 45/100] finished: 02:14:07 | elapsed=35.169s | total_elapsed=1940.458s
[eta 46/100] started: 02:14:07 | eta=(1.0, 1.0, 0.09920814661883615, 0.15846546322618482, 0.28300000000000003)
[eta 46] MC started: 02:14:07 (30 repeats x 4 options)
[eta 46] MC finished: 02:14:16 | elapsed=8.448s
[eta 46] CVAE started: 02:14:16 (30 repeats)
[eta 46] CVAE finished: 02:14:17 | elapsed=1.026s
[eta 46/100] finished: 02:14:17 | elapsed=9.481s | total_elapsed=1949.939s
[eta 47/100] started: 02:14:17 | eta=(1.0, 1.0, 0.09588017621528666, 0.16239645549532708, 1.344)
[eta 47] MC started: 02:14:17 (30 repeats x 4 options)
[eta 47] MC finished: 02:14:56 | elapsed=39.048s
[eta 47] CVAE started: 02:14:56 (30 repeats)
[eta 47] CVAE finished: 02:14:57 | elapsed=1.031s
[eta 47/100] finished: 02:14:57 | elapsed=40.088s | total_elapsed=1990.028s
[eta 48/100] started: 02:14:57 | eta=(1.0, 1.0, 0.07919641352916398, 0.2843534451798771, 2.187)
[eta 48] MC started: 02:14:57 (30 repeats x 4 options)
[eta 48] MC finished: 02:16:01 | elapsed=64.513s
[eta 48] CVAE started: 02:16:01 (30 repeats)
[eta 48] CVAE finished: 02:16:02 | elapsed=1.051s
[eta 48/100] finished: 02:16:02 | elapsed=65.572s | total_elapsed=2055.601s
[eta 49/100] started: 02:16:02 | eta=(1.0, 1.0, 0.02852509600245098, 0.5371693195385019, 2.327)
[eta 49] MC started: 02:16:02 (30 repeats x 4 options)
[eta 49] MC finished: 02:17:11 | elapsed=68.990s
[eta 49] CVAE started: 02:17:11 (30 repeats)
[eta 49] CVAE finished: 02:17:12 | elapsed=1.015s
[eta 49/100] finished: 02:17:12 | elapsed=70.012s | total_elapsed=2125.613s
[eta 50/100] started: 02:17:12 | eta=(1.0, 1.0, 0.062491670530591105, 0.7734654761783173, 0.664)
[eta 50] MC started: 02:17:12 (30 repeats x 4 options)
[eta 50] MC finished: 02:17:32 | elapsed=19.877s
[eta 50] CVAE started: 02:17:32 (30 repeats)
[eta 50] CVAE finished: 02:17:33 | elapsed=1.020s
[eta 50/100] finished: 02:17:33 | elapsed=20.906s | total_elapsed=2146.520s
[eta 51/100] started: 02:17:33 | eta=(1.0, 1.0, 0.005387368514623659, 0.5983574161529026, 0.786)
[eta 51] MC started: 02:17:33 (30 repeats x 4 options)
[eta 51] MC finished: 02:17:57 | elapsed=23.564s
[eta 51] CVAE started: 02:17:57 (30 repeats)
[eta 51] CVAE finished: 02:17:58 | elapsed=1.113s
[eta 51/100] finished: 02:17:58 | elapsed=24.684s | total_elapsed=2171.205s
[eta 52/100] started: 02:17:58 | eta=(1.0, 1.0, 0.09820047415219546, 0.5376394964734547, 1.022)
[eta 52] MC started: 02:17:58 (30 repeats x 4 options)
[eta 52] MC finished: 02:18:28 | elapsed=30.608s
[eta 52] CVAE started: 02:18:28 (30 repeats)
[eta 52] CVAE finished: 02:18:30 | elapsed=1.064s
[eta 52/100] finished: 02:18:30 | elapsed=31.679s | total_elapsed=2202.885s
[eta 53/100] started: 02:18:30 | eta=(1.0, 1.0, 0.01193808979262484, 0.05321415983056284, 2.5140000000000002)
[eta 53] MC started: 02:18:30 (30 repeats x 4 options)
[eta 53] MC finished: 02:19:45 | elapsed=75.550s
[eta 53] CVAE started: 02:19:45 (30 repeats)
[eta 53] CVAE finished: 02:19:46 | elapsed=1.012s
[eta 53/100] finished: 02:19:46 | elapsed=76.569s | total_elapsed=2279.454s
[eta 54/100] started: 02:19:46 | eta=(1.0, 1.0, 0.07385230561433469, 0.7834005170921748, 1.102)
[eta 54] MC started: 02:19:46 (30 repeats x 4 options)
[eta 54] MC finished: 02:20:30 | elapsed=43.432s
[eta 54] CVAE started: 02:20:30 (30 repeats)

In [44]:
# BS FDM delta: 100개 eta, closed-form 기준 MAE/MSE
import time
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display

BS_FDM_OPTION_SPECS = {
    "van_call": ("call", None),
    "van_put": ("put", None),
    "barr_call": ("call", 0.8),
    "barr_put": ("put", 0.8),
}
BS_FDM_SOLVER_KWARGS = {"S_max": 4.0, "dS": 0.005, "dt": 0.0005}
BS_FDM_DELTA_H = 0.01

if len(bs_para) != 100:
    raise ValueError(f"bs_para는 100개여야 합니다: {len(bs_para)}개")

bs_fdm_rows = []
bs_fdm_started_at = time.perf_counter()

for set_idx, (r, sigma, T) in enumerate(bs_para):
    eta = (
        1.0, 1.0, float(r), float(sigma),
        round(float(T) / MC_DT) * MC_DT,
    )

    for option, (opt_type, barrier) in BS_FDM_OPTION_SPECS.items():
        closed_form_delta = BS_greeks(
            eta, type=opt_type, B=barrier, h={"delta": BS_FDM_DELTA_H}
        )["delta"]
        fdm_result = FDM_BS_greeks(
            eta,
            B=barrier,
            opt_type=opt_type,
            greeks=("delta",),
            h={"S0": BS_FDM_DELTA_H},
            solver_kwargs=BS_FDM_SOLVER_KWARGS,
        )
        fdm_delta = float(fdm_result["delta"])
        error = fdm_delta - closed_form_delta
        bs_fdm_rows.append({
            "set_idx": set_idx,
            "option": option,
            "opt_type": opt_type,
            "barrier": barrier,
            "S0": eta[0],
            "K": eta[1],
            "r": eta[2],
            "sigma": eta[3],
            "T": eta[4],
            "closed_form_delta": closed_form_delta,
            "fdm_delta": fdm_delta,
            "fdm_abs_error": abs(error),
            "fdm_squared_error": error**2,
            "delta_h": BS_FDM_DELTA_H,
        })

    print(
        f"BS FDM: {set_idx + 1}/{len(bs_para)} eta completed | "
        f"elapsed={time.perf_counter() - bs_fdm_started_at:.1f}s",
        flush=True,
    )

bs_fdm_details = pd.DataFrame(bs_fdm_rows)
bs_fdm_mae_mse = (
    bs_fdm_details
    .groupby("option", sort=False)[["fdm_abs_error", "fdm_squared_error"]]
    .mean()
    .rename(columns={
        "fdm_abs_error": "FDM MAE vs closed-form",
        "fdm_squared_error": "FDM MSE vs closed-form",
    })
)

bs_fdm_output_dir = Path("result/greeks/mae")
bs_fdm_output_dir.mkdir(parents=True, exist_ok=True)
bs_fdm_details_path = bs_fdm_output_dir / "bs_fdm_delta_100eta_details.csv"
bs_fdm_summary_path = bs_fdm_output_dir / "bs_fdm_delta_100eta_summary.csv"
bs_fdm_details.to_csv(bs_fdm_details_path, index=False)
bs_fdm_mae_mse.to_csv(bs_fdm_summary_path)

display(bs_fdm_mae_mse)
print(f"Saved: {bs_fdm_details_path}")
print(f"Saved: {bs_fdm_summary_path}")

BS FDM: 1/100 eta completed | elapsed=0.3s
BS FDM: 2/100 eta completed | elapsed=0.8s
BS FDM: 3/100 eta completed | elapsed=1.0s
BS FDM: 4/100 eta completed | elapsed=1.6s
BS FDM: 5/100 eta completed | elapsed=1.8s
BS FDM: 6/100 eta completed | elapsed=3.2s
BS FDM: 7/100 eta completed | elapsed=4.7s
BS FDM: 8/100 eta completed | elapsed=6.0s
BS FDM: 9/100 eta completed | elapsed=6.3s
BS FDM: 10/100 eta completed | elapsed=7.2s
BS FDM: 11/100 eta completed | elapsed=8.6s
BS FDM: 12/100 eta completed | elapsed=10.1s
BS FDM: 13/100 eta completed | elapsed=10.3s
BS FDM: 14/100 eta completed | elapsed=10.8s
BS FDM: 15/100 eta completed | elapsed=11.9s
BS FDM: 16/100 eta completed | elapsed=13.0s
BS FDM: 17/100 eta completed | elapsed=14.0s
BS FDM: 18/100 eta completed | elapsed=15.2s
BS FDM: 19/100 eta completed | elapsed=15.8s
BS FDM: 20/100 eta completed | elapsed=16.1s
BS FDM: 21/100 eta completed | elapsed=17.3s
BS FDM: 22/100 eta completed | elapsed=17.9s
BS FDM: 23/100 eta completed | elapsed=18.1s
BS FDM: 24/100 eta completed | elapsed=19.2s
BS FDM: 25/100 eta completed | elapsed=20.6s
BS FDM: 26/100 eta completed | elapsed=20.9s
BS FDM: 27/100 eta completed | elapsed=21.6s
BS FDM: 28/100 eta completed | elapsed=22.2s
BS FDM: 29/100 eta completed | elapsed=22.4s
BS FDM: 30/100 eta completed | elapsed=23.1s
BS FDM: 31/100 eta completed | elapsed=23.3s
BS FDM: 32/100 eta completed | elapsed=23.7s
BS FDM: 33/100 eta completed | elapsed=24.4s
BS FDM: 34/100 eta completed | elapsed=25.6s
BS FDM: 35/100 eta completed | elapsed=25.9s
BS FDM: 36/100 eta completed | elapsed=27.3s
BS FDM: 37/100 eta completed | elapsed=27.9s
BS FDM: 38/100 eta completed | elapsed=28.2s
BS FDM: 39/100 eta completed | elapsed=28.4s
BS FDM: 40/100 eta completed | elapsed=29.8s
BS FDM: 41/100 eta completed | elapsed=30.1s
BS FDM: 42/100 eta completed | elapsed=31.1s
BS FDM: 43/100 eta completed | elapsed=32.1s
BS FDM: 44/100 eta completed | elapsed=32.7s
BS FDM: 45/100 eta completed | elapsed=33.3s
BS FDM: 46/100 eta completed | elapsed=33.5s
BS FDM: 47/100 eta completed | elapsed=34.2s
BS FDM: 48/100 eta completed | elapsed=35.3s
BS FDM: 49/100 eta completed | elapsed=36.5s
BS FDM: 50/100 eta completed | elapsed=36.9s
BS FDM: 51/100 eta completed | elapsed=37.3s
BS FDM: 52/100 eta completed | elapsed=37.8s
BS FDM: 53/100 eta completed | elapsed=39.1s
BS FDM: 54/100 eta completed | elapsed=39.7s
BS FDM: 55/100 eta completed | elapsed=40.1s
BS FDM: 56/100 eta completed | elapsed=41.0s
BS FDM: 57/100 eta completed | elapsed=41.4s
BS FDM: 58/100 eta completed | elapsed=41.6s
BS FDM: 59/100 eta completed | elapsed=42.5s
BS FDM: 60/100 eta completed | elapsed=43.4s
BS FDM: 61/100 eta completed | elapsed=44.6s
BS FDM: 62/100 eta completed | elapsed=46.1s
BS FDM: 63/100 eta completed | elapsed=46.6s
BS FDM: 64/100 eta completed | elapsed=47.2s
BS FDM: 65/100 eta completed | elapsed=47.8s
BS FDM: 66/100 eta completed | elapsed=48.8s
BS FDM: 67/100 eta completed | elapsed=49.1s
BS FDM: 68/100 eta completed | elapsed=50.2s
BS FDM: 69/100 eta completed | elapsed=50.5s
BS FDM: 70/100 eta completed | elapsed=50.6s
BS FDM: 71/100 eta completed | elapsed=51.6s
BS FDM: 72/100 eta completed | elapsed=51.9s
BS FDM: 73/100 eta completed | elapsed=52.5s
BS FDM: 74/100 eta completed | elapsed=53.3s
BS FDM: 75/100 eta completed | elapsed=54.5s
BS FDM: 76/100 eta completed | elapsed=54.6s
BS FDM: 77/100 eta completed | elapsed=55.5s
BS FDM: 78/100 eta completed | elapsed=57.1s
BS FDM: 79/100 eta completed | elapsed=57.5s
BS FDM: 80/100 eta completed | elapsed=58.4s
BS FDM: 81/100 eta completed | elapsed=59.7s
BS FDM: 82/100 eta completed | elapsed=60.2s
BS FDM: 83/100 eta completed | elapsed=61.7s
BS FDM: 84/100 eta completed | elapsed=62.1s
BS FDM: 85/100 eta completed | elapsed=62.5s
BS FDM: 86/100 eta completed | elapsed=62.8s
BS FDM: 87/100 eta completed | elapsed=63.6s
BS FDM: 88/100 eta completed | elapsed=64.1s
BS FDM: 89/100 eta completed | elapsed=64.9s
BS FDM: 90/100 eta completed | elapsed=65.1s
BS FDM: 91/100 eta completed | elapsed=65.7s
BS FDM: 92/100 eta completed | elapsed=66.5s
BS FDM: 93/100 eta completed | elapsed=67.7s
BS FDM: 94/100 eta completed | elapsed=68.8s
BS FDM: 95/100 eta completed | elapsed=69.2s
BS FDM: 96/100 eta completed | elapsed=69.3s
BS FDM: 97/100 eta completed | elapsed=69.8s
BS FDM: 98/100 eta completed | elapsed=70.4s
BS FDM: 99/100 eta completed | elapsed=70.5s
BS FDM: 100/100 eta completed | elapsed=71.3s

           FDM MAE vs closed-form  FDM MSE vs closed-form
option
van_call                 0.009247            2.379105e-04
van_put                  0.009247            2.379105e-04
barr_call                0.000884            6.496744e-06
barr_put                 0.000122            8.449320e-08

Saved: result/greeks/mae/bs_fdm_delta_100eta_details.csv
Saved: result/greeks/mae/bs_fdm_delta_100eta_summary.csv

In [9]:
# BS CVAE-AD delta: 100개 eta, closed-form 기준 MAE/MSE
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from IPython.display import display

from e_3_CVAE_greek_AD import CVAE_greeks_AD

BS_AD_N_SAMPLES = 100_000
BS_AD_REPEATS = 30
BS_AD_SEED_STRIDE = 10_000
BS_AD_BARRIER = 0.8
BS_AD_OPTION_SPECS = {
    "van_call": ("call", None),
    "van_put": ("put", None),
    "barr_call": ("call", BS_AD_BARRIER),
    "barr_put": ("put", BS_AD_BARRIER),
}

if "bs_cvae" not in globals() or "bs_ckpt" not in globals():
    raise RuntimeError("먼저 BS CVAE 모델 설정 셀을 실행하세요.")
if np.asarray(bs_para).shape != (100, 3):
    raise ValueError(f"bs_para shape은 (100, 3)이어야 합니다: {np.asarray(bs_para).shape}")

bs_ad_output_dir = Path("result/greeks/mae")
bs_ad_output_dir.mkdir(parents=True, exist_ok=True)
bs_ad_details_path = bs_ad_output_dir / (
    "bs_cvae_ad_delta_100eta_100k_30rep_details.csv"
)
bs_ad_summary_path = bs_ad_output_dir / (
    "bs_cvae_ad_delta_100eta_100k_30rep_summary.csv"
)

# 완료된 eta 결과를 불러와 중단 지점부터 이어서 계산합니다.
if bs_ad_details_path.exists():
    bs_ad_rows = pd.read_csv(bs_ad_details_path).to_dict("records")
    bs_ad_existing = pd.DataFrame(bs_ad_rows)
    completed_set_idxs = set(
        bs_ad_existing.groupby("set_idx").filter(
            lambda group: set(group["option"]) == set(BS_AD_OPTION_SPECS)
        )["set_idx"].astype(int)
    )
    print(f"기존 BS AD 결과 {len(completed_set_idxs)}/100 eta를 불러왔습니다.")
else:
    bs_ad_rows = []
    completed_set_idxs = set()

bs_ad_started_at = time.perf_counter()
for set_idx, (r, sigma, T) in enumerate(bs_para):
    if set_idx in completed_set_idxs:
        continue

    eta = (
        1.0, 1.0, float(r), float(sigma),
        round(float(T) / MC_DT) * MC_DT,
    )
    delta_h = max(abs(eta[0]) * 0.01, 1e-6)
    closed_form_delta = {
        option: BS_greeks(
            eta, type=opt_type, B=barrier, h={"delta": delta_h}
        )["delta"]
        for option, (opt_type, barrier) in BS_AD_OPTION_SPECS.items()
    }
    ad_values = {option: [] for option in BS_AD_OPTION_SPECS}
    base_seed = 1234 + set_idx * 100

    for repeat_idx in range(BS_AD_REPEATS):
        with warnings.catch_warnings():
            warnings.filterwarnings(
                "ignore",
                message="Hard-indicator AD is a frozen-indicator diagnostic.*",
                category=RuntimeWarning,
            )
            ad_result = CVAE_greeks_AD(
                bs_cvae,
                bs_ckpt,
                eta,
                model_type="bs",
                B=BS_AD_BARRIER,
                greeks=("delta",),
                n_samples=BS_AD_N_SAMPLES,
                antithetic=True,
                seed=base_seed + repeat_idx * BS_AD_SEED_STRIDE,
            )
        for option in BS_AD_OPTION_SPECS:
            ad_values[option].append(ad_result["greeks"]["delta"][option])

    for option, values in ad_values.items():
        ad_delta = float(np.mean(values))
        error = ad_delta - float(closed_form_delta[option])
        bs_ad_rows.append({
            "set_idx": set_idx,
            "option": option,
            "opt_type": BS_AD_OPTION_SPECS[option][0],
            "barrier": BS_AD_OPTION_SPECS[option][1],
            "S0": eta[0],
            "K": eta[1],
            "r": eta[2],
            "sigma": eta[3],
            "T": eta[4],
            "closed_form_delta": float(closed_form_delta[option]),
            "cvae_ad_delta": ad_delta,
            "cvae_ad_abs_error": abs(error),
            "cvae_ad_squared_error": error**2,
            "n_samples": BS_AD_N_SAMPLES,
            "repeat_count": BS_AD_REPEATS,
            "delta_h": delta_h,
            "barrier_estimator": (
                "frozen_indicator_pathwise" if option.startswith("barr_") else None
            ),
        })

    completed_set_idxs.add(set_idx)
    pd.DataFrame(bs_ad_rows).to_csv(bs_ad_details_path, index=False)
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    print(
        f"BS AD: {len(completed_set_idxs)}/100 eta completed | "
        f"elapsed={time.perf_counter() - bs_ad_started_at:.1f}s",
        flush=True,
    )

bs_ad_details = (
    pd.DataFrame(bs_ad_rows)
    .sort_values(["set_idx", "option"])
    .reset_index(drop=True)
)
if len(bs_ad_details) != 400:
    raise RuntimeError("일부 BS AD 계산이 완료되지 않았습니다. 셀을 다시 실행하세요.")

bs_ad_mae_mse = (
    bs_ad_details
    .groupby("option", sort=False)[
        ["cvae_ad_abs_error", "cvae_ad_squared_error"]
    ]
    .mean()
    .rename(columns={
        "cvae_ad_abs_error": "CVAE-AD MAE vs closed-form",
        "cvae_ad_squared_error": "CVAE-AD MSE vs closed-form",
    })
)
bs_ad_details.to_csv(bs_ad_details_path, index=False)
bs_ad_mae_mse.to_csv(bs_ad_summary_path)

display(bs_ad_mae_mse)
print("주의: barrier AD delta는 frozen-indicator pathwise 추정치입니다.")
print(f"Saved: {bs_ad_details_path}")
print(f"Saved: {bs_ad_summary_path}")

BS AD: 1/100 eta completed | elapsed=6.7s
BS AD: 2/100 eta completed | elapsed=13.0s
BS AD: 3/100 eta completed | elapsed=19.0s
BS AD: 4/100 eta completed | elapsed=24.9s
BS AD: 5/100 eta completed | elapsed=30.8s
BS AD: 6/100 eta completed | elapsed=36.8s
BS AD: 7/100 eta completed | elapsed=42.7s
BS AD: 8/100 eta completed | elapsed=48.6s
BS AD: 9/100 eta completed | elapsed=54.7s
BS AD: 10/100 eta completed | elapsed=61.0s
BS AD: 11/100 eta completed | elapsed=67.1s
BS AD: 12/100 eta completed | elapsed=73.1s
BS AD: 13/100 eta completed | elapsed=79.2s
BS AD: 14/100 eta completed | elapsed=85.3s
BS AD: 15/100 eta completed | elapsed=91.1s
BS AD: 16/100 eta completed | elapsed=97.1s
BS AD: 17/100 eta completed | elapsed=103.1s
BS AD: 18/100 eta completed | elapsed=109.0s
BS AD: 19/100 eta completed | elapsed=114.9s
BS AD: 20/100 eta completed | elapsed=121.0s
BS AD: 21/100 eta completed | elapsed=126.9s
BS AD: 22/100 eta completed | elapsed=132.9s
BS AD: 23/100 eta completed | elapsed=139.0s
BS AD: 24/100 eta completed | elapsed=145.1s
BS AD: 25/100 eta completed | elapsed=151.3s
BS AD: 26/100 eta completed | elapsed=157.4s
BS AD: 27/100 eta completed | elapsed=163.4s
BS AD: 28/100 eta completed | elapsed=169.4s
BS AD: 29/100 eta completed | elapsed=175.3s
BS AD: 30/100 eta completed | elapsed=181.3s
BS AD: 31/100 eta completed | elapsed=187.1s
BS AD: 32/100 eta completed | elapsed=192.9s
BS AD: 33/100 eta completed | elapsed=198.6s
BS AD: 34/100 eta completed | elapsed=204.4s
BS AD: 35/100 eta completed | elapsed=210.4s
BS AD: 36/100 eta completed | elapsed=216.4s
BS AD: 37/100 eta completed | elapsed=222.1s
BS AD: 38/100 eta completed | elapsed=228.0s
BS AD: 39/100 eta completed | elapsed=233.9s
BS AD: 40/100 eta completed | elapsed=239.9s
BS AD: 41/100 eta completed | elapsed=245.9s
BS AD: 42/100 eta completed | elapsed=252.0s
BS AD: 43/100 eta completed | elapsed=258.0s
BS AD: 44/100 eta completed | elapsed=264.1s
BS AD: 45/100 eta completed | elapsed=270.2s
BS AD: 46/100 eta completed | elapsed=276.2s
BS AD: 47/100 eta completed | elapsed=282.2s
BS AD: 48/100 eta completed | elapsed=288.2s
BS AD: 49/100 eta completed | elapsed=294.2s
BS AD: 50/100 eta completed | elapsed=300.2s
BS AD: 51/100 eta completed | elapsed=306.3s
BS AD: 52/100 eta completed | elapsed=312.2s
BS AD: 53/100 eta completed | elapsed=318.1s
BS AD: 54/100 eta completed | elapsed=324.2s
BS AD: 55/100 eta completed | elapsed=330.1s
BS AD: 56/100 eta completed | elapsed=336.1s
BS AD: 57/100 eta completed | elapsed=342.0s
BS AD: 58/100 eta completed | elapsed=347.9s
BS AD: 59/100 eta completed | elapsed=353.9s
BS AD: 60/100 eta completed | elapsed=359.9s
BS AD: 61/100 eta completed | elapsed=365.8s
BS AD: 62/100 eta completed | elapsed=371.8s
BS AD: 63/100 eta completed | elapsed=378.0s
BS AD: 64/100 eta completed | elapsed=383.9s
BS AD: 65/100 eta completed | elapsed=389.8s
BS AD: 66/100 eta completed | elapsed=395.7s
BS AD: 67/100 eta completed | elapsed=401.6s
BS AD: 68/100 eta completed | elapsed=407.5s
BS AD: 69/100 eta completed | elapsed=413.5s
BS AD: 70/100 eta completed | elapsed=419.5s
BS AD: 71/100 eta completed | elapsed=425.5s
BS AD: 72/100 eta completed | elapsed=431.5s
BS AD: 73/100 eta completed | elapsed=437.5s
BS AD: 74/100 eta completed | elapsed=443.5s
BS AD: 75/100 eta completed | elapsed=449.3s
BS AD: 76/100 eta completed | elapsed=455.1s
BS AD: 77/100 eta completed | elapsed=461.2s
BS AD: 78/100 eta completed | elapsed=467.1s
BS AD: 79/100 eta completed | elapsed=472.9s
BS AD: 80/100 eta completed | elapsed=478.7s
BS AD: 81/100 eta completed | elapsed=484.4s
BS AD: 82/100 eta completed | elapsed=490.3s
BS AD: 83/100 eta completed | elapsed=496.2s
BS AD: 84/100 eta completed | elapsed=502.1s
BS AD: 85/100 eta completed | elapsed=507.9s
BS AD: 86/100 eta completed | elapsed=513.8s
BS AD: 87/100 eta completed | elapsed=519.7s
BS AD: 88/100 eta completed | elapsed=525.7s
BS AD: 89/100 eta completed | elapsed=531.6s
BS AD: 90/100 eta completed | elapsed=537.6s
BS AD: 91/100 eta completed | elapsed=543.7s
BS AD: 92/100 eta completed | elapsed=549.5s
BS AD: 93/100 eta completed | elapsed=555.5s
BS AD: 94/100 eta completed | elapsed=561.5s
BS AD: 95/100 eta completed | elapsed=567.5s
BS AD: 96/100 eta completed | elapsed=573.4s
BS AD: 97/100 eta completed | elapsed=579.3s
BS AD: 98/100 eta completed | elapsed=585.2s
BS AD: 99/100 eta completed | elapsed=591.1s
BS AD: 100/100 eta completed | elapsed=597.1s

           CVAE-AD MAE vs closed-form  CVAE-AD MSE vs closed-form
option
barr_call                    0.344845                    0.191367
barr_put                     0.051445                    0.006389
van_call                     0.075404                    0.535737
van_put                      0.000897                    0.000002

주의: barrier AD delta는 frozen-indicator pathwise 추정치입니다.
Saved: result/greeks/mae/bs_cvae_ad_delta_100eta_100k_30rep_details.csv
Saved: result/greeks/mae/bs_cvae_ad_delta_100eta_100k_30rep_summary.csv

In [26]:
from pathlib import Path

bs_delta_results = pd.DataFrame(bs_delta_rows)
bs_error_specs = (
    ("mc", "100k"),
    ("cvae", "100k"),
)

for method, sample_size in bs_error_specs:
    error = (
        bs_delta_results[f"{method}_{sample_size}_delta"]
        - bs_delta_results["closed_form_delta"]
    )
    bs_delta_results[f"{method}_{sample_size}_abs_error"] = error.abs()
    bs_delta_results[f"{method}_{sample_size}_squared_error"] = error.pow(2)

bs_summary_columns = {}
for method, sample_size in bs_error_specs:
    bs_summary_columns[f"{method}_{sample_size}_abs_error"] = (
        f"{method.upper()} {sample_size} MAE vs closed-form"
    )
    bs_summary_columns[f"{method}_{sample_size}_squared_error"] = (
        f"{method.upper()} {sample_size} MSE vs closed-form"
    )

bs_delta_mae_mse = (
    bs_delta_results
    .groupby("option", sort=False)[list(bs_summary_columns)]
    .mean()
    .rename(columns=bs_summary_columns)
)

mae_output_dir = Path("result/greeks/mae")
mae_output_dir.mkdir(parents=True, exist_ok=True)

first_eta = bs_delta_results.iloc[0]
file_stem = (
    f"{first_eta['r']:.5f}_{first_eta['sigma']:.5f}_{first_eta['T']:.5f}_"
    f"h_value_{first_eta['delta_h']:.5f}_{first_eta['rho_h']:.5f}_"
    f"{first_eta['vega_h']:.5f}_{first_eta['theta_h']:.5f}_"
    "bs_delta_mae_mse_100k"
)
details_path = mae_output_dir / f"{file_stem}_details.csv"
summary_path = mae_output_dir / f"{file_stem}_summary.csv"

bs_delta_results.to_csv(details_path, index=False)
bs_delta_mae_mse.to_csv(summary_path)

display(bs_delta_mae_mse)
print(f"MC_REPEATS: {int(bs_delta_results['mc_repeat_count'].iloc[0])}")
print(f"CVAE_REPEATS: {int(bs_delta_results['cvae_repeat_count'].iloc[0])}")
print(f"Saved: {details_path}")
print(f"Saved: {summary_path}")

,MC 100k MAE vs closed-form,MC 100k MSE vs closed-form,CVAE 100k MAE vs closed-form,CVAE 100k MSE vs closed-form
option,,,,
van_call,0.008416,2.202797e-04,0.082793,0.536114
van_put,0.008457,2.204009e-04,0.008776,0.000252
barr_call,0.002485,2.258731e-05,0.027496,0.001458
barr_put,0.000255,1.870156e-07,0.001121,0.000003

MC_REPEATS: 30
CVAE_REPEATS: 30
Saved: result/greeks/mae/0.01915_0.18408_0.59100_h_value_0.01000_0.00019_0.00184_0.00591_bs_delta_mae_mse_100k_details.csv
Saved: result/greeks/mae/0.01915_0.18408_0.59100_h_value_0.01000_0.00019_0.00184_0.00591_bs_delta_mae_mse_100k_summary.csv

In [8]:
validate_samples= False
valid_resample  = validate_samples
multiple        = 50

In [10]:
# BS CVAE delta: X_T tail 재추출, closed-form 기준 MAE/MSE
import importlib
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from IPython.display import display

import e_3_CVAE_greek
importlib.reload(e_3_CVAE_greek)
from e_3_CVAE_greek import CVAE_greeks

BS_CVAE_N_SAMPLES = 100_000
BS_CVAE_REPEATS = 30
BS_CVAE_SEED_STRIDE = 10_000
BS_CVAE_MULTIPLE = multiple  # X_T >= log(10), 즉 S_T >= 10*S0이면 재추출
BS_CVAE_OPTION_SPECS = {
    "van_call": ("call", None),
    "van_put": ("put", None),
    "barr_call": ("call", 0.8),
    "barr_put": ("put", 0.8),
}

if "bs_cvae" not in globals() or "bs_ckpt" not in globals():
    raise RuntimeError("먼저 BS CVAE 모델 설정 셀을 실행하세요.")
if np.asarray(bs_para).shape != (100, 3):
    raise ValueError(f"bs_para shape은 (100, 3)이어야 합니다: {np.asarray(bs_para).shape}")
if BS_CVAE_MULTIPLE != 0 and BS_CVAE_MULTIPLE <= 1:
    raise ValueError("BS_CVAE_MULTIPLE은 0 또는 1보다 큰 값이어야 합니다.")

bs_cvae_multiple_tag = f"multiple{BS_CVAE_MULTIPLE:g}"
bs_cvae_output_dir = Path("result/greeks/mae")
bs_cvae_output_dir.mkdir(parents=True, exist_ok=True)
bs_cvae_details_path = bs_cvae_output_dir / (
    f"bs_cvae_delta_100eta_100k_30rep_{bs_cvae_multiple_tag}_details.csv"
)
bs_cvae_summary_path = bs_cvae_output_dir / (
    f"bs_cvae_delta_100eta_100k_30rep_{bs_cvae_multiple_tag}_summary.csv"
)

if bs_cvae_details_path.exists():
    bs_cvae_rows = pd.read_csv(bs_cvae_details_path).to_dict("records")
    bs_cvae_existing = pd.DataFrame(bs_cvae_rows)
    completed_set_idxs = set(
        bs_cvae_existing.groupby("set_idx").filter(
            lambda group: set(group["option"]) == set(BS_CVAE_OPTION_SPECS)
        )["set_idx"].astype(int)
    )
    print(f"기존 BS CVAE 결과 {len(completed_set_idxs)}/100 eta를 불러왔습니다.")
else:
    bs_cvae_rows = []
    completed_set_idxs = set()

bs_cvae_started_at = time.perf_counter()
for set_idx, (r, sigma, T) in enumerate(bs_para):
    if set_idx in completed_set_idxs:
        continue

    eta = (
        1.0, 1.0, float(r), float(sigma),
        round(float(T) / MC_DT) * MC_DT,
    )
    delta_h = max(abs(eta[0]) * 0.01, 1e-6)
    greek_h = {"delta": delta_h}
    closed_form_delta = {
        option: BS_greeks(eta, type=opt_type, B=barrier, h=greek_h)["delta"]
        for option, (opt_type, barrier) in BS_CVAE_OPTION_SPECS.items()
    }
    cvae_values = {option: [] for option in BS_CVAE_OPTION_SPECS}
    rejected_fractions = []
    base_seed = 1234 + set_idx * 100

    for repeat_idx in range(BS_CVAE_REPEATS):
        cvae_result = CVAE_greeks(
            bs_cvae,
            bs_ckpt,
            eta,
            model_type="bs",
            B=0.8,
            greeks=("delta",),
            n_samples=BS_CVAE_N_SAMPLES,
            h=greek_h,
            antithetic=True,
            seed=base_seed + repeat_idx * BS_CVAE_SEED_STRIDE,
            validate_samples=validate_samples,
            valid_resample=valid_resample,
            multiple=BS_CVAE_MULTIPLE,
        )
        for option in BS_CVAE_OPTION_SPECS:
            cvae_values[option].append(cvae_result["greeks"]["delta"][option])
        rejected_fractions.append(
            cvae_result["sampling_diagnostics"]["tail_rejected_sample_fraction"]
        )

    for option, values in cvae_values.items():
        cvae_delta = float(np.mean(values))
        error = cvae_delta - float(closed_form_delta[option])
        bs_cvae_rows.append({
            "set_idx": set_idx,
            "option": option,
            "opt_type": BS_CVAE_OPTION_SPECS[option][0],
            "barrier": BS_CVAE_OPTION_SPECS[option][1],
            "S0": eta[0],
            "K": eta[1],
            "r": eta[2],
            "sigma": eta[3],
            "T": eta[4],
            "closed_form_delta": float(closed_form_delta[option]),
            "cvae_100k_delta": cvae_delta,
            "cvae_100k_abs_error": abs(error),
            "cvae_100k_squared_error": error**2,
            "n_samples": BS_CVAE_N_SAMPLES,
            "repeat_count": BS_CVAE_REPEATS,
            "delta_h": delta_h,
            "multiple": BS_CVAE_MULTIPLE,
            "X_T_upper": (
                np.log(BS_CVAE_MULTIPLE) if BS_CVAE_MULTIPLE > 0 else np.nan
            ),
            "mean_tail_rejected_fraction": float(np.mean(rejected_fractions)),
        })

    completed_set_idxs.add(set_idx)
    pd.DataFrame(bs_cvae_rows).to_csv(bs_cvae_details_path, index=False)
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    print(
        f"BS CVAE: {len(completed_set_idxs)}/100 eta completed | "
        f"tail rejected={np.mean(rejected_fractions):.4%} | "
        f"elapsed={time.perf_counter() - bs_cvae_started_at:.1f}s",
        flush=True,
    )

bs_cvae_details = (
    pd.DataFrame(bs_cvae_rows)
    .sort_values(["set_idx", "option"])
    .reset_index(drop=True)
)
if len(bs_cvae_details) != 400:
    raise RuntimeError("일부 BS CVAE 계산이 완료되지 않았습니다. 셀을 다시 실행하세요.")

bs_cvae_mae_mse = (
    bs_cvae_details
    .groupby("option", sort=False)[
        ["cvae_100k_abs_error", "cvae_100k_squared_error"]
    ]
    .mean()
    .rename(columns={
        "cvae_100k_abs_error": "CVAE 100k MAE vs closed-form",
        "cvae_100k_squared_error": "CVAE 100k MSE vs closed-form",
    })
)
bs_cvae_details.to_csv(bs_cvae_details_path, index=False)
bs_cvae_mae_mse.to_csv(bs_cvae_summary_path)

display(bs_cvae_mae_mse)
print(f"X_T 재추출 기준: X_T >= log({BS_CVAE_MULTIPLE:g})")
print(f"Saved: {bs_cvae_details_path}")
print(f"Saved: {bs_cvae_summary_path}")

BS CVAE: 1/100 eta completed | tail rejected=0.0000% | elapsed=1.0s
BS CVAE: 2/100 eta completed | tail rejected=0.0000% | elapsed=2.1s
BS CVAE: 3/100 eta completed | tail rejected=0.0000% | elapsed=3.1s
BS CVAE: 4/100 eta completed | tail rejected=0.0000% | elapsed=4.1s
BS CVAE: 5/100 eta completed | tail rejected=0.0000% | elapsed=5.2s
BS CVAE: 6/100 eta completed | tail rejected=0.0316% | elapsed=7.2s
BS CVAE: 7/100 eta completed | tail rejected=0.0601% | elapsed=9.3s
BS CVAE: 8/100 eta completed | tail rejected=0.0081% | elapsed=11.3s
BS CVAE: 9/100 eta completed | tail rejected=0.0000% | elapsed=12.4s
BS CVAE: 10/100 eta completed | tail rejected=0.0000% | elapsed=13.4s
BS CVAE: 11/100 eta completed | tail rejected=0.0481% | elapsed=15.4s
BS CVAE: 12/100 eta completed | tail rejected=0.0070% | elapsed=17.5s
BS CVAE: 13/100 eta completed | tail rejected=0.0000% | elapsed=18.5s
BS CVAE: 14/100 eta completed | tail rejected=0.0000% | elapsed=19.6s
BS CVAE: 15/100 eta completed | tail rejected=0.0000% | elapsed=20.6s
BS CVAE: 16/100 eta completed | tail rejected=0.0000% | elapsed=21.6s
BS CVAE: 17/100 eta completed | tail rejected=0.0000% | elapsed=22.7s
BS CVAE: 18/100 eta completed | tail rejected=0.0368% | elapsed=24.7s
BS CVAE: 19/100 eta completed | tail rejected=0.0000% | elapsed=25.8s
BS CVAE: 20/100 eta completed | tail rejected=0.0000% | elapsed=26.8s
BS CVAE: 21/100 eta completed | tail rejected=0.0000% | elapsed=27.9s
BS CVAE: 22/100 eta completed | tail rejected=0.0000% | elapsed=28.9s
BS CVAE: 23/100 eta completed | tail rejected=0.0000% | elapsed=29.9s
BS CVAE: 24/100 eta completed | tail rejected=0.0000% | elapsed=31.1s
BS CVAE: 25/100 eta completed | tail rejected=0.0000% | elapsed=32.1s
BS CVAE: 26/100 eta completed | tail rejected=0.0000% | elapsed=33.1s
BS CVAE: 27/100 eta completed | tail rejected=0.0013% | elapsed=34.9s
BS CVAE: 28/100 eta completed | tail rejected=0.0000% | elapsed=35.9s
BS CVAE: 29/100 eta completed | tail rejected=0.0000% | elapsed=37.0s
BS CVAE: 30/100 eta completed | tail rejected=0.0000% | elapsed=38.0s
BS CVAE: 31/100 eta completed | tail rejected=0.0000% | elapsed=39.1s
BS CVAE: 32/100 eta completed | tail rejected=0.0000% | elapsed=40.1s
BS CVAE: 33/100 eta completed | tail rejected=0.0000% | elapsed=41.1s
BS CVAE: 34/100 eta completed | tail rejected=0.0002% | elapsed=42.4s
BS CVAE: 35/100 eta completed | tail rejected=0.0000% | elapsed=43.5s
BS CVAE: 36/100 eta completed | tail rejected=0.0000% | elapsed=44.5s
BS CVAE: 37/100 eta completed | tail rejected=0.0000% | elapsed=45.6s
BS CVAE: 38/100 eta completed | tail rejected=0.0000% | elapsed=46.6s
BS CVAE: 39/100 eta completed | tail rejected=0.0000% | elapsed=47.6s
BS CVAE: 40/100 eta completed | tail rejected=0.0000% | elapsed=48.7s
BS CVAE: 41/100 eta completed | tail rejected=0.0000% | elapsed=49.7s
BS CVAE: 42/100 eta completed | tail rejected=0.0000% | elapsed=50.8s
BS CVAE: 43/100 eta completed | tail rejected=0.0008% | elapsed=52.5s
BS CVAE: 44/100 eta completed | tail rejected=0.0000% | elapsed=53.5s
BS CVAE: 45/100 eta completed | tail rejected=0.0000% | elapsed=54.6s
BS CVAE: 46/100 eta completed | tail rejected=0.0000% | elapsed=55.6s
BS CVAE: 47/100 eta completed | tail rejected=0.0000% | elapsed=56.6s
BS CVAE: 48/100 eta completed | tail rejected=0.0000% | elapsed=57.7s
BS CVAE: 49/100 eta completed | tail rejected=0.0000% | elapsed=58.7s
BS CVAE: 50/100 eta completed | tail rejected=0.0000% | elapsed=59.8s
BS CVAE: 51/100 eta completed | tail rejected=0.0000% | elapsed=60.8s
BS CVAE: 52/100 eta completed | tail rejected=0.0000% | elapsed=61.8s
BS CVAE: 53/100 eta completed | tail rejected=0.0000% | elapsed=62.9s
BS CVAE: 54/100 eta completed | tail rejected=0.0000% | elapsed=64.0s
BS CVAE: 55/100 eta completed | tail rejected=0.0000% | elapsed=65.0s
BS CVAE: 56/100 eta completed | tail rejected=0.0000% | elapsed=66.0s
BS CVAE: 57/100 eta completed | tail rejected=0.0000% | elapsed=67.1s
BS CVAE: 58/100 eta completed | tail rejected=0.0000% | elapsed=68.1s
BS CVAE: 59/100 eta completed | tail rejected=0.0000% | elapsed=69.1s
BS CVAE: 60/100 eta completed | tail rejected=0.0000% | elapsed=70.2s
BS CVAE: 61/100 eta completed | tail rejected=0.0000% | elapsed=71.2s
BS CVAE: 62/100 eta completed | tail rejected=0.0000% | elapsed=72.3s
BS CVAE: 63/100 eta completed | tail rejected=0.0000% | elapsed=73.3s
BS CVAE: 64/100 eta completed | tail rejected=0.0001% | elapsed=74.5s
BS CVAE: 65/100 eta completed | tail rejected=0.0000% | elapsed=75.5s
BS CVAE: 66/100 eta completed | tail rejected=0.0036% | elapsed=77.6s
BS CVAE: 67/100 eta completed | tail rejected=0.0000% | elapsed=78.6s
BS CVAE: 68/100 eta completed | tail rejected=0.0000% | elapsed=79.7s
BS CVAE: 69/100 eta completed | tail rejected=0.0000% | elapsed=80.7s
BS CVAE: 70/100 eta completed | tail rejected=0.0000% | elapsed=81.7s
BS CVAE: 71/100 eta completed | tail rejected=0.0000% | elapsed=82.8s
BS CVAE: 72/100 eta completed | tail rejected=0.0000% | elapsed=83.8s
BS CVAE: 73/100 eta completed | tail rejected=0.0000% | elapsed=84.8s
BS CVAE: 74/100 eta completed | tail rejected=0.0000% | elapsed=85.9s
BS CVAE: 75/100 eta completed | tail rejected=0.0006% | elapsed=87.5s
BS CVAE: 76/100 eta completed | tail rejected=0.0000% | elapsed=88.5s
BS CVAE: 77/100 eta completed | tail rejected=0.0001% | elapsed=89.7s
BS CVAE: 78/100 eta completed | tail rejected=0.0000% | elapsed=90.8s
BS CVAE: 79/100 eta completed | tail rejected=0.0000% | elapsed=91.8s
BS CVAE: 80/100 eta completed | tail rejected=0.0000% | elapsed=92.9s
BS CVAE: 81/100 eta completed | tail rejected=0.0031% | elapsed=94.8s
BS CVAE: 82/100 eta completed | tail rejected=0.0000% | elapsed=95.9s
BS CVAE: 83/100 eta completed | tail rejected=0.0261% | elapsed=97.9s
BS CVAE: 84/100 eta completed | tail rejected=0.0000% | elapsed=99.0s
BS CVAE: 85/100 eta completed | tail rejected=0.0000% | elapsed=100.0s
BS CVAE: 86/100 eta completed | tail rejected=0.0000% | elapsed=101.0s
BS CVAE: 87/100 eta completed | tail rejected=0.0000% | elapsed=102.1s
BS CVAE: 88/100 eta completed | tail rejected=0.0000% | elapsed=103.1s
BS CVAE: 89/100 eta completed | tail rejected=0.0000% | elapsed=104.2s
BS CVAE: 90/100 eta completed | tail rejected=0.0000% | elapsed=105.2s
BS CVAE: 91/100 eta completed | tail rejected=0.0001% | elapsed=106.5s
BS CVAE: 92/100 eta completed | tail rejected=0.0003% | elapsed=107.8s
BS CVAE: 93/100 eta completed | tail rejected=0.0002% | elapsed=109.1s
BS CVAE: 94/100 eta completed | tail rejected=0.0000% | elapsed=110.2s
BS CVAE: 95/100 eta completed | tail rejected=0.0000% | elapsed=111.2s
BS CVAE: 96/100 eta completed | tail rejected=0.0000% | elapsed=112.3s
BS CVAE: 97/100 eta completed | tail rejected=0.0000% | elapsed=113.3s
BS CVAE: 98/100 eta completed | tail rejected=0.0000% | elapsed=114.4s
BS CVAE: 99/100 eta completed | tail rejected=0.0000% | elapsed=115.4s
BS CVAE: 100/100 eta completed | tail rejected=0.0000% | elapsed=116.5s

           CVAE 100k MAE vs closed-form  CVAE 100k MSE vs closed-form
option
barr_call                      0.030698                      0.002148
barr_put                       0.001121                      0.000003
van_call                       0.010044                      0.000288
van_put                        0.008773                      0.000252

X_T 재추출 기준: X_T >= log(50)
Saved: result/greeks/mae/bs_cvae_delta_100eta_100k_30rep_multiple50_details.csv
Saved: result/greeks/mae/bs_cvae_delta_100eta_100k_30rep_multiple50_summary.csv

In [7]:
MC_DT = 0.001
hes_para = generate_heston_params(n_sets=100, seed=1234)
hes_para[:, 6] = np.round(hes_para[:, 6] / MC_DT) * MC_DT

In [32]:
import numpy as np

from e_0_generate import generate_heston_params

MC_DT = 0.001
HESTON_COLUMNS = ["r", "kappa", "theta", "xi", "rho", "Y0", "T"]
HESTON_RANGES = {
    "r": (0.0025, 0.0975),
    "kappa": (1.3, 4.5),
    "theta": (0.035, 0.15),
    "xi": (0.15, 0.60),
    "rho": (-0.95, -0.05),
    "Y0": (0.005, 0.15),
    "T": (0.15, 2.85),
}


def generate_heston_params_in_range(n_sets=100, seed=1234):
    """모든 지정 범위를 동시에 만족하는 Heston 파라미터를 생성합니다."""
    accepted_batches = []
    n_accepted = 0
    batch_index = 0

    while n_accepted < n_sets:
        # 여러 범위를 동시에 통과해야 하므로 후보를 넉넉하게 생성합니다.
        batch_size = max(1000, 20 * (n_sets - n_accepted))
        candidates = generate_heston_params(
            n_sets=batch_size,
            seed=seed if batch_index == 0 else None,
        )
        candidates[:, 6] = np.round(candidates[:, 6] / MC_DT) * MC_DT

        valid = np.ones(batch_size, dtype=bool)
        for column_index, parameter in enumerate(HESTON_COLUMNS):
            lower, upper = HESTON_RANGES[parameter]
            valid &= candidates[:, column_index] >= lower
            valid &= candidates[:, column_index] <= upper

        accepted = candidates[valid]
        if len(accepted):
            accepted_batches.append(accepted)
            n_accepted += len(accepted)
        batch_index += 1

    return np.vstack(accepted_batches)[:n_sets]


# 다음 Heston MAE 셀이 그대로 사용할 변수명입니다.
hes_para = generate_heston_params_in_range(n_sets=100, seed=1234)

hes_range_checks = {}
for column_index, parameter in enumerate(HESTON_COLUMNS):
    lower, upper = HESTON_RANGES[parameter]
    values = hes_para[:, column_index]
    hes_range_checks[parameter] = bool(np.all((values >= lower) & (values <= upper)))

assert hes_para.shape == (100, 7)
assert all(hes_range_checks.values())
print(f"생성된 Heston eta: {len(hes_para)}개")
print("범위 검증:", hes_range_checks)

생성된 Heston eta: 100개
범위 검증: {'r': True, 'kappa': True, 'theta': True, 'xi': True, 'rho': True, 'Y0': True, 'T': True}

In [35]:
# Heston delta MAE/MSE: MC with 100,000 paths is the reference. 219m
import pandas as pd

if "hes_cvae" not in globals() or "hes_ckpt" not in globals():
    raise RuntimeError("Run the Heston CVAE setup cell before this cell.")

OPTION_SPECS = {
    "van_call": ("call", None),
    "van_put": ("put", None),
    "barr_call": ("call", 0.8),
    "barr_put": ("put", 0.8),
}

MC_REPEATS = 30
CVAE_REPEATS = 30
REPEAT_SEED_STRIDE = 10_000
ratio = 0.01
n_samples = 10_000
hes_delta_rows = []

for row_idx, (r, kappa, long_var, xi, corr, v0, T) in enumerate(hes_para):
    T = round(float(T) / 0.001) * 0.001
    eta = (
        1.0, 1.0, float(r), float(kappa), float(long_var),
        float(xi), float(corr), float(v0), T,
    )
    hes_greek_h = {
        "delta": max(abs(eta[0]) * ratio, 1e-6),
        "rho": max(abs(eta[2]) * ratio, 1e-6),
        "v0": max(abs(eta[7]) * ratio, 1e-6),
        "theta": max(abs(eta[8]) * ratio, 1e-6),
    }
    seed = 1234 + row_idx * 100

    mc_values = {option: [] for option in OPTION_SPECS}
    for repeat_idx in range(MC_REPEATS):
        repeat_seed = seed + repeat_idx * REPEAT_SEED_STRIDE
        for option, (opt_type, B) in OPTION_SPECS.items():
            mc_result = MC_heston_greeks_gpu(
                eta,
                B=B,
                opt_type=opt_type,
                greeks=("delta",),
                n_paths=n_samples,
                dt=0.001,
                h=hes_greek_h,
                seed=repeat_seed,
                antithetic=True,
            )
            mc_values[option].append(mc_result["delta"])

    cvae_values = {option: [] for option in OPTION_SPECS}
    for repeat_idx in range(CVAE_REPEATS):
        repeat_seed = seed + repeat_idx * REPEAT_SEED_STRIDE
        cvae_result = CVAE_greeks(
            hes_cvae,
            hes_ckpt,
            eta,
            model_type="hes",
            B=0.8,
            greeks=("delta",),
            n_samples=n_samples,
            h=hes_greek_h,
            antithetic=True,
            seed=repeat_seed,
        )
        for option in OPTION_SPECS:
            cvae_values[option].append(cvae_result["greeks"]["delta"][option])

    mc_delta = {
        option: float(np.mean(values))
        for option, values in mc_values.items()
    }
    cvae_delta = {
        option: float(np.mean(values))
        for option, values in cvae_values.items()
    }

    for option in OPTION_SPECS:
        hes_delta_rows.append(
            {
                "set_idx": row_idx,
                "option": option,
                "opt_type": OPTION_SPECS[option][0],
                "barrier": OPTION_SPECS[option][1],
                "S0": eta[0],
                "K": eta[1],
                "r": eta[2],
                "kappa": eta[3],
                "long_var": eta[4],
                "xi": eta[5],
                "corr": eta[6],
                "v0": eta[7],
                "T": eta[8],
                "mc_10k_delta": mc_delta[option],
                "cvae_10k_delta": cvae_delta[option],
                "mc_reference_n_paths": n_samples,
                "mc_dt": 0.001,
                "mc_seed": seed,
                "cvae_100k_n_samples": n_samples,
                "cvae_seed": seed,
                "mc_repeat_count": MC_REPEATS,
                "cvae_repeat_count": CVAE_REPEATS,
                "repeat_seed_stride": REPEAT_SEED_STRIDE,
                "delta_h": hes_greek_h["delta"],
                "rho_h": hes_greek_h["rho"],
                "v0_h": hes_greek_h["v0"],
                "theta_h": hes_greek_h["theta"],
            }
        )

    print(
        f"Heston: {row_idx + 1}/{len(hes_para)} completed "
        f"(MC={MC_REPEATS}, CVAE={CVAE_REPEATS}, samples={n_samples:,})"
    )

Heston: 1/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 2/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 3/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 4/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 5/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 6/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 7/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 8/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 9/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 10/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 11/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 12/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 13/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 14/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 15/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 16/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 17/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 18/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 19/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 20/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 21/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 22/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 23/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 24/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 25/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 26/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 27/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 28/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 29/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 30/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 31/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 32/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 33/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 34/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 35/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 36/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 37/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 38/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 39/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 40/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 41/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 42/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 43/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 44/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 45/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 46/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 47/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 48/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 49/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 50/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 51/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 52/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 53/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 54/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 55/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 56/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 57/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 58/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 59/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 60/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 61/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 62/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 63/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 64/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 65/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 66/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 67/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 68/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 69/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 70/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 71/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 72/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 73/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 74/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 75/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 76/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 77/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 78/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 79/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 80/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 81/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 82/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 83/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 84/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 85/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 86/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 87/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 88/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 89/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 90/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 91/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 92/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 93/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 94/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 95/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 96/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 97/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 98/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 99/100 completed (MC=30, CVAE=30, samples=10,000)
Heston: 100/100 completed (MC=30, CVAE=30, samples=10,000)

In [20]:
# 38번 셀: Heston FDM delta, 기존 MC 100k 결과 기준 MAE/MSE
import math
import time
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display

HESTON_MC_100K_PATH = Path(
    "result/greeks/mae/"
    "0.01915_0.10041_2.43300_h_value_0.01000_0.00019_0.00100_0.02433_"
    "hes_delta_mae_mse_100k_details.csv"
)
HESTON_FDM_D_S = 0.01
HESTON_FDM_D_V = 0.0001
HESTON_FDM_TARGET_D_T = 0.01
HESTON_FDM_S_MAX = 4.0
HESTON_FDM_V_MAX = 1.5

hes_mc_100k = pd.read_csv(HESTON_MC_100K_PATH)
required_columns = [
    "set_idx", "option", "opt_type", "barrier",
    "S0", "K", "r", "kappa", "long_var", "xi", "corr",
    "v0", "T", "delta_h", "mc_100k_delta",
]
missing_columns = [
    column for column in required_columns if column not in hes_mc_100k.columns
]
if missing_columns:
    raise ValueError(f"MC 100k CSV에 필요한 열이 없습니다: {missing_columns}")
if hes_mc_100k["set_idx"].nunique() != 100:
    raise ValueError("MC 100k CSV에는 서로 다른 eta가 정확히 100개 있어야 합니다.")
if hes_mc_100k.duplicated(["set_idx", "option"]).any():
    raise ValueError("MC 100k CSV의 set_idx/option 키가 중복되었습니다.")

# 현재 생성된 100개 hes_para와 참조 CSV의 eta가 같은지 확인합니다.
reference_eta_columns = ["r", "kappa", "long_var", "xi", "corr", "v0", "T"]
reference_eta = (
    hes_mc_100k[["set_idx", *reference_eta_columns]]
    .drop_duplicates()
    .sort_values("set_idx")[reference_eta_columns]
    .to_numpy()
)
if np.asarray(hes_para).shape != (100, 7) or not np.allclose(
    reference_eta, np.asarray(hes_para), rtol=1e-12, atol=1e-12
):
    raise ValueError("현재 hes_para와 MC 100k 참조 CSV의 eta가 일치하지 않습니다.")

hes_fdm_output_dir = Path("result/greeks/mae")
hes_fdm_output_dir.mkdir(parents=True, exist_ok=True)
hes_fdm_details_path = hes_fdm_output_dir / "hes_fdm_delta_100eta_vs_mc_100k_details.csv"
hes_fdm_summary_path = hes_fdm_output_dir / "hes_fdm_delta_100eta_vs_mc_100k_summary.csv"

# 긴 계산이 중단되어도 재실행 시 완료된 set_idx/option부터 이어갑니다.
if hes_fdm_details_path.exists():
    hes_fdm_rows = pd.read_csv(hes_fdm_details_path).to_dict("records")
    completed_keys = {
        (int(row["set_idx"]), row["option"]) for row in hes_fdm_rows
    }
    print(f"기존 결과 {len(completed_keys)}개를 불러와 이어서 계산합니다.")
else:
    hes_fdm_rows = []
    completed_keys = set()

hes_fdm_started_at = time.perf_counter()
reference_rows = hes_mc_100k.sort_values(["set_idx", "option"])

for reference in reference_rows.itertuples(index=False):
    key = (int(reference.set_idx), reference.option)
    if key in completed_keys:
        continue

    eta = (
        float(reference.S0),
        float(reference.K),
        float(reference.r),
        float(reference.kappa),
        float(reference.long_var),
        float(reference.xi),
        float(reference.corr),
        float(reference.v0),
        float(reference.T),
    )
    barrier = None if pd.isna(reference.barrier) else float(reference.barrier)

    # T를 변경하지 않으면서 약 0.01 간격의 정수 time step을 사용합니다.
    n_time_steps = max(1, math.ceil(eta[-1] / HESTON_FDM_TARGET_D_T))
    fdm_dt = eta[-1] / n_time_steps
    solver_kwargs = {
        "S_max": HESTON_FDM_S_MAX,
        "v_max": HESTON_FDM_V_MAX,
        "dS": HESTON_FDM_D_S,
        "dv": HESTON_FDM_D_V,
        "dt": fdm_dt,
    }

    row_started_at = time.perf_counter()
    fdm_result = FDM_heston_greeks(
        eta,
        B=barrier,
        opt_type=reference.opt_type,
        greeks=("delta",),
        h={"S0": float(reference.delta_h)},
        solver_kwargs=solver_kwargs,
    )
    fdm_delta = float(fdm_result["delta"])
    mc_100k_delta = float(reference.mc_100k_delta)
    error = fdm_delta - mc_100k_delta

    hes_fdm_rows.append({
        "set_idx": key[0],
        "option": key[1],
        "opt_type": reference.opt_type,
        "barrier": barrier,
        "S0": eta[0],
        "K": eta[1],
        "r": eta[2],
        "kappa": eta[3],
        "long_var": eta[4],
        "xi": eta[5],
        "corr": eta[6],
        "v0": eta[7],
        "T": eta[8],
        "mc_100k_delta": mc_100k_delta,
        "fdm_delta": fdm_delta,
        "fdm_abs_error_vs_mc_100k": abs(error),
        "fdm_squared_error_vs_mc_100k": error**2,
        "delta_h": float(reference.delta_h),
        "fdm_dS": HESTON_FDM_D_S,
        "fdm_dv": HESTON_FDM_D_V,
        "fdm_dt": fdm_dt,
        "elapsed_seconds": time.perf_counter() - row_started_at,
    })
    completed_keys.add(key)

    # 한 옵션이 끝날 때마다 저장해 중단 시 계산 결과를 보존합니다.
    pd.DataFrame(hes_fdm_rows).to_csv(hes_fdm_details_path, index=False)
    print(
        f"Heston FDM: {len(completed_keys)}/{len(reference_rows)} completed | "
        f"set_idx={key[0]}, option={key[1]} | "
        f"total_elapsed={time.perf_counter() - hes_fdm_started_at:.1f}s",
        flush=True,
    )

hes_fdm_details = (
    pd.DataFrame(hes_fdm_rows)
    .sort_values(["set_idx", "option"])
    .reset_index(drop=True)
)
if len(hes_fdm_details) != len(reference_rows):
    raise RuntimeError("일부 Heston FDM 계산이 완료되지 않았습니다. 셀을 다시 실행하세요.")

hes_fdm_mae_mse = (
    hes_fdm_details
    .groupby("option", sort=False)[
        ["fdm_abs_error_vs_mc_100k", "fdm_squared_error_vs_mc_100k"]
    ]
    .mean()
    .rename(columns={
        "fdm_abs_error_vs_mc_100k": "FDM MAE vs MC 100k",
        "fdm_squared_error_vs_mc_100k": "FDM MSE vs MC 100k",
    })
)
hes_fdm_details.to_csv(hes_fdm_details_path, index=False)
hes_fdm_mae_mse.to_csv(hes_fdm_summary_path)

display(hes_fdm_mae_mse)
print(f"Reference: {HESTON_MC_100K_PATH}")
print(f"Saved: {hes_fdm_details_path}")
print(f"Saved: {hes_fdm_summary_path}")

Calculating base
Calculating base finish
Heston FDM: 1/400 completed | set_idx=0, option=barr_call | total_elapsed=351.2s
Calculating base
Calculating base finish
Heston FDM: 2/400 completed | set_idx=0, option=barr_put | total_elapsed=698.3s
Calculating base
Calculating base finish
Heston FDM: 3/400 completed | set_idx=0, option=van_call | total_elapsed=1087.4s
Calculating base
Calculating base finish
Heston FDM: 4/400 completed | set_idx=0, option=van_put | total_elapsed=1478.7s
Calculating base
Calculating base finish
Heston FDM: 5/400 completed | set_idx=1, option=barr_call | total_elapsed=1590.9s
Calculating base
Calculating base finish
Heston FDM: 6/400 completed | set_idx=1, option=barr_put | total_elapsed=1702.8s
Calculating base
Calculating base finish
Heston FDM: 7/400 completed | set_idx=1, option=van_call | total_elapsed=1827.5s
Calculating base
Calculating base finish
Heston FDM: 8/400 completed | set_idx=1, option=van_put | total_elapsed=1952.5s
Calculating base
Calculating base finish
Heston FDM: 9/400 completed | set_idx=2, option=barr_call | total_elapsed=2132.5s
Calculating base
Calculating base finish
Heston FDM: 10/400 completed | set_idx=2, option=barr_put | total_elapsed=2311.3s
Calculating base
Calculating base finish
Heston FDM: 11/400 completed | set_idx=2, option=van_call | total_elapsed=2511.8s
Calculating base
Calculating base finish
Heston FDM: 12/400 completed | set_idx=2, option=van_put | total_elapsed=2713.2s
Calculating base
Calculating base finish
Heston FDM: 13/400 completed | set_idx=3, option=barr_call | total_elapsed=2933.6s
Calculating base
Calculating base finish
Heston FDM: 14/400 completed | set_idx=3, option=barr_put | total_elapsed=3154.3s
Calculating base
Calculating base finish
Heston FDM: 15/400 completed | set_idx=3, option=van_call | total_elapsed=3399.7s
Calculating base
Calculating base finish
Heston FDM: 16/400 completed | set_idx=3, option=van_put | total_elapsed=3645.7s
Calculating base
Calculating base finish
Heston FDM: 17/400 completed | set_idx=4, option=barr_call | total_elapsed=3866.8s
Calculating base
Calculating base finish
Heston FDM: 18/400 completed | set_idx=4, option=barr_put | total_elapsed=4087.8s
Calculating base
Calculating base finish
Heston FDM: 19/400 completed | set_idx=4, option=van_call | total_elapsed=4336.6s
Calculating base
Calculating base finish
Heston FDM: 20/400 completed | set_idx=4, option=van_put | total_elapsed=4588.4s
Calculating base
Calculating base finish
Heston FDM: 21/400 completed | set_idx=5, option=barr_call | total_elapsed=4741.4s
Calculating base
Calculating base finish
Heston FDM: 22/400 completed | set_idx=5, option=barr_put | total_elapsed=4894.4s
Calculating base
Calculating base finish
Heston FDM: 23/400 completed | set_idx=5, option=van_call | total_elapsed=5067.6s
Calculating base
Calculating base finish
Heston FDM: 24/400 completed | set_idx=5, option=van_put | total_elapsed=5244.4s
Calculating base
Calculating base finish
Heston FDM: 25/400 completed | set_idx=6, option=barr_call | total_elapsed=5304.0s
Calculating base
Calculating base finish
Heston FDM: 26/400 completed | set_idx=6, option=barr_put | total_elapsed=5364.0s
Calculating base
Calculating base finish
Heston FDM: 27/400 completed | set_idx=6, option=van_call | total_elapsed=5432.1s
Calculating base
Calculating base finish
Heston FDM: 28/400 completed | set_idx=6, option=van_put | total_elapsed=5500.4s
Calculating base
Calculating base finish
Heston FDM: 29/400 completed | set_idx=7, option=barr_call | total_elapsed=5781.7s
Calculating base
Calculating base finish
Heston FDM: 30/400 completed | set_idx=7, option=barr_put | total_elapsed=6062.6s
Calculating base
Calculating base finish
Heston FDM: 31/400 completed | set_idx=7, option=van_call | total_elapsed=6379.8s
Calculating base
Calculating base finish
Heston FDM: 32/400 completed | set_idx=7, option=van_put | total_elapsed=6697.3s
Calculating base
Calculating base finish
Heston FDM: 33/400 completed | set_idx=8, option=barr_call | total_elapsed=6774.7s
Calculating base
Calculating base finish
Heston FDM: 34/400 completed | set_idx=8, option=barr_put | total_elapsed=6852.3s
Calculating base
Calculating base finish
Heston FDM: 35/400 completed | set_idx=8, option=van_call | total_elapsed=6941.7s
Calculating base
Calculating base finish
Heston FDM: 36/400 completed | set_idx=8, option=van_put | total_elapsed=7030.3s
Calculating base
Calculating base finish
Heston FDM: 37/400 completed | set_idx=9, option=barr_call | total_elapsed=7125.7s
Calculating base
Calculating base finish
Heston FDM: 38/400 completed | set_idx=9, option=barr_put | total_elapsed=7221.4s
Calculating base
Calculating base finish
Heston FDM: 39/400 completed | set_idx=9, option=van_call | total_elapsed=7330.0s
Calculating base
Calculating base finish
Heston FDM: 40/400 completed | set_idx=9, option=van_put | total_elapsed=7439.5s
Calculating base
Calculating base finish
Heston FDM: 41/400 completed | set_idx=10, option=barr_call | total_elapsed=7479.7s
Calculating base
Calculating base finish
Heston FDM: 42/400 completed | set_idx=10, option=barr_put | total_elapsed=7519.2s
Calculating base
Calculating base finish
Heston FDM: 43/400 completed | set_idx=10, option=van_call | total_elapsed=7563.7s
Calculating base
Calculating base finish
Heston FDM: 44/400 completed | set_idx=10, option=van_put | total_elapsed=7608.7s
Calculating base
Calculating base finish
Heston FDM: 45/400 completed | set_idx=11, option=barr_call | total_elapsed=8004.3s
Calculating base
Calculating base finish
Heston FDM: 46/400 completed | set_idx=11, option=barr_put | total_elapsed=8397.2s
Calculating base
Calculating base finish
Heston FDM: 47/400 completed | set_idx=11, option=van_call | total_elapsed=8842.5s
Calculating base
Calculating base finish
Heston FDM: 48/400 completed | set_idx=11, option=van_put | total_elapsed=9287.8s
Calculating base
Calculating base finish
Heston FDM: 49/400 completed | set_idx=12, option=barr_call | total_elapsed=9647.1s
Calculating base
Calculating base finish
Heston FDM: 50/400 completed | set_idx=12, option=barr_put | total_elapsed=10005.4s
Calculating base
Calculating base finish
Heston FDM: 51/400 completed | set_idx=12, option=van_call | total_elapsed=10411.2s
Calculating base
Calculating base finish
Heston FDM: 52/400 completed | set_idx=12, option=van_put | total_elapsed=10817.6s
Calculating base
Calculating base finish
Heston FDM: 53/400 completed | set_idx=13, option=barr_call | total_elapsed=10899.7s
Calculating base
Calculating base finish
Heston FDM: 54/400 completed | set_idx=13, option=barr_put | total_elapsed=10980.7s
Calculating base
Calculating base finish
Heston FDM: 55/400 completed | set_idx=13, option=van_call | total_elapsed=11074.4s
Calculating base
Calculating base finish
Heston FDM: 56/400 completed | set_idx=13, option=van_put | total_elapsed=11168.3s
Calculating base
Calculating base finish
Heston FDM: 57/400 completed | set_idx=14, option=barr_call | total_elapsed=11544.0s
Calculating base
Calculating base finish
Heston FDM: 58/400 completed | set_idx=14, option=barr_put | total_elapsed=11916.9s
Calculating base
Calculating base finish
Heston FDM: 59/400 completed | set_idx=14, option=van_call | total_elapsed=12340.5s
Calculating base
Calculating base finish
Heston FDM: 60/400 completed | set_idx=14, option=van_put | total_elapsed=12762.8s
Calculating base
Calculating base finish
Heston FDM: 61/400 completed | set_idx=15, option=barr_call | total_elapsed=12989.9s
Calculating base
Calculating base finish
Heston FDM: 62/400 completed | set_idx=15, option=barr_put | total_elapsed=13217.6s
Calculating base
Calculating base finish
Heston FDM: 63/400 completed | set_idx=15, option=van_call | total_elapsed=13473.3s
Calculating base
Calculating base finish
Heston FDM: 64/400 completed | set_idx=15, option=van_put | total_elapsed=13731.7s
Calculating base
Calculating base finish
Heston FDM: 65/400 completed | set_idx=16, option=barr_call | total_elapsed=13800.3s
Calculating base
Calculating base finish
Heston FDM: 66/400 completed | set_idx=16, option=barr_put | total_elapsed=13869.8s
Calculating base
Calculating base finish
Heston FDM: 67/400 completed | set_idx=16, option=van_call | total_elapsed=13948.0s
Calculating base
Calculating base finish
Heston FDM: 68/400 completed | set_idx=16, option=van_put | total_elapsed=14025.6s
Calculating base
Calculating base finish
Heston FDM: 69/400 completed | set_idx=17, option=barr_call | total_elapsed=14087.6s
Calculating base
Calculating base finish
Heston FDM: 70/400 completed | set_idx=17, option=barr_put | total_elapsed=14149.1s
Calculating base
Calculating base finish
Heston FDM: 71/400 completed | set_idx=17, option=van_call | total_elapsed=14219.3s
Calculating base
Calculating base finish
Heston FDM: 72/400 completed | set_idx=17, option=van_put | total_elapsed=14289.4s
Calculating base
Calculating base finish
Heston FDM: 73/400 completed | set_idx=18, option=barr_call | total_elapsed=14395.9s
Calculating base
Calculating base finish
Heston FDM: 74/400 completed | set_idx=18, option=barr_put | total_elapsed=14502.8s
Calculating base
Calculating base finish
Heston FDM: 75/400 completed | set_idx=18, option=van_call | total_elapsed=14625.0s
Calculating base
Calculating base finish
Heston FDM: 76/400 completed | set_idx=18, option=van_put | total_elapsed=14747.0s
Calculating base
Calculating base finish
Heston FDM: 77/400 completed | set_idx=19, option=barr_call | total_elapsed=15129.0s
Calculating base
Calculating base finish
Heston FDM: 78/400 completed | set_idx=19, option=barr_put | total_elapsed=15506.3s
Calculating base
Calculating base finish
Heston FDM: 79/400 completed | set_idx=19, option=van_call | total_elapsed=15941.5s
Calculating base
Calculating base finish
Heston FDM: 80/400 completed | set_idx=19, option=van_put | total_elapsed=16376.7s
Calculating base
Calculating base finish
Heston FDM: 81/400 completed | set_idx=20, option=barr_call | total_elapsed=16575.7s
Calculating base
Calculating base finish
Heston FDM: 82/400 completed | set_idx=20, option=barr_put | total_elapsed=16774.3s
Calculating base
Calculating base finish
Heston FDM: 83/400 completed | set_idx=20, option=van_call | total_elapsed=17001.3s
Calculating base
Calculating base finish
Heston FDM: 84/400 completed | set_idx=20, option=van_put | total_elapsed=17227.9s
Calculating base
Calculating base finish
Heston FDM: 85/400 completed | set_idx=21, option=barr_call | total_elapsed=17523.7s
Calculating base
Calculating base finish
Heston FDM: 86/400 completed | set_idx=21, option=barr_put | total_elapsed=17826.6s
Calculating base
Calculating base finish
Heston FDM: 87/400 completed | set_idx=21, option=van_call | total_elapsed=18170.9s
Calculating base
Calculating base finish
Heston FDM: 88/400 completed | set_idx=21, option=van_put | total_elapsed=18517.0s
Calculating base
Calculating base finish
Heston FDM: 89/400 completed | set_idx=22, option=barr_call | total_elapsed=18694.4s
Calculating base
Calculating base finish
Heston FDM: 90/400 completed | set_idx=22, option=barr_put | total_elapsed=18871.4s
Calculating base
Calculating base finish
Heston FDM: 91/400 completed | set_idx=22, option=van_call | total_elapsed=19072.2s
Calculating base
Calculating base finish
Heston FDM: 92/400 completed | set_idx=22, option=van_put | total_elapsed=19272.4s
Calculating base
Calculating base finish
Heston FDM: 93/400 completed | set_idx=23, option=barr_call | total_elapsed=19543.3s
Calculating base
Calculating base finish
Heston FDM: 94/400 completed | set_idx=23, option=barr_put | total_elapsed=19813.0s
Calculating base
Calculating base finish
Heston FDM: 95/400 completed | set_idx=23, option=van_call | total_elapsed=20120.7s
Calculating base
Calculating base finish
Heston FDM: 96/400 completed | set_idx=23, option=van_put | total_elapsed=20429.7s
Calculating base
Calculating base finish
Heston FDM: 97/400 completed | set_idx=24, option=barr_call | total_elapsed=20734.2s
Calculating base
Calculating base finish
Heston FDM: 98/400 completed | set_idx=24, option=barr_put | total_elapsed=21041.5s
Calculating base
Calculating base finish
Heston FDM: 99/400 completed | set_idx=24, option=van_call | total_elapsed=21392.7s
Calculating base
Calculating base finish
Heston FDM: 100/400 completed | set_idx=24, option=van_put | total_elapsed=21743.5s
Calculating base
Calculating base finish
Heston FDM: 101/400 completed | set_idx=25, option=barr_call | total_elapsed=21964.0s
Calculating base
Calculating base finish
Heston FDM: 102/400 completed | set_idx=25, option=barr_put | total_elapsed=22185.0s
Calculating base
Calculating base finish
Heston FDM: 103/400 completed | set_idx=25, option=van_call | total_elapsed=22436.4s
Calculating base
Calculating base finish
Heston FDM: 104/400 completed | set_idx=25, option=van_put | total_elapsed=22690.5s
Calculating base
Calculating base finish
Heston FDM: 105/400 completed | set_idx=26, option=barr_call | total_elapsed=23015.6s
Calculating base
Calculating base finish
Heston FDM: 106/400 completed | set_idx=26, option=barr_put | total_elapsed=23341.9s
Calculating base
Calculating base finish
Heston FDM: 107/400 completed | set_idx=26, option=van_call | total_elapsed=23713.6s
Calculating base
Calculating base finish
Heston FDM: 108/400 completed | set_idx=26, option=van_put | total_elapsed=24086.2s
Calculating base
Calculating base finish
Heston FDM: 109/400 completed | set_idx=27, option=barr_call | total_elapsed=24443.7s
Calculating base
Calculating base finish
Heston FDM: 110/400 completed | set_idx=27, option=barr_put | total_elapsed=24799.2s
Calculating base
Calculating base finish
Heston FDM: 111/400 completed | set_idx=27, option=van_call | total_elapsed=25206.9s
Calculating base
Calculating base finish
Heston FDM: 112/400 completed | set_idx=27, option=van_put | total_elapsed=25613.9s
Calculating base
Calculating base finish
Heston FDM: 113/400 completed | set_idx=28, option=barr_call | total_elapsed=25860.1s
Calculating base
Calculating base finish
Heston FDM: 114/400 completed | set_idx=28, option=barr_put | total_elapsed=26105.9s
Calculating base
Calculating base finish
Heston FDM: 115/400 completed | set_idx=28, option=van_call | total_elapsed=26386.7s
Calculating base
Calculating base finish
Heston FDM: 116/400 completed | set_idx=28, option=van_put | total_elapsed=26667.6s
Calculating base
Calculating base finish
Heston FDM: 117/400 completed | set_idx=29, option=barr_call | total_elapsed=26906.6s
Calculating base
Calculating base finish
Heston FDM: 118/400 completed | set_idx=29, option=barr_put | total_elapsed=27148.0s
Calculating base
Calculating base finish
Heston FDM: 119/400 completed | set_idx=29, option=van_call | total_elapsed=27423.5s
Calculating base
Calculating base finish
Heston FDM: 120/400 completed | set_idx=29, option=van_put | total_elapsed=27697.6s
Calculating base
Calculating base finish
Heston FDM: 121/400 completed | set_idx=30, option=barr_call | total_elapsed=27956.9s
Calculating base
Calculating base finish
Heston FDM: 122/400 completed | set_idx=30, option=barr_put | total_elapsed=28213.6s
Calculating base
Calculating base finish
Heston FDM: 123/400 completed | set_idx=30, option=van_call | total_elapsed=28508.6s
Calculating base
Calculating base finish
Heston FDM: 124/400 completed | set_idx=30, option=van_put | total_elapsed=28802.8s
Calculating base
Calculating base finish
Heston FDM: 125/400 completed | set_idx=31, option=barr_call | total_elapsed=28830.1s
Calculating base
Calculating base finish
Heston FDM: 126/400 completed | set_idx=31, option=barr_put | total_elapsed=28857.4s
Calculating base
Calculating base finish
Heston FDM: 127/400 completed | set_idx=31, option=van_call | total_elapsed=28888.0s
Calculating base
Calculating base finish
Heston FDM: 128/400 completed | set_idx=31, option=van_put | total_elapsed=28918.7s
Calculating base
Calculating base finish
Heston FDM: 129/400 completed | set_idx=32, option=barr_call | total_elapsed=29342.9s
Calculating base
Calculating base finish
Heston FDM: 130/400 completed | set_idx=32, option=barr_put | total_elapsed=29763.1s
Calculating base
Calculating base finish
Heston FDM: 131/400 completed | set_idx=32, option=van_call | total_elapsed=30241.4s
Calculating base
Calculating base finish
Heston FDM: 132/400 completed | set_idx=32, option=van_put | total_elapsed=30721.2s
Calculating base
Calculating base finish
Heston FDM: 133/400 completed | set_idx=33, option=barr_call | total_elapsed=30766.4s
Calculating base
Calculating base finish
Heston FDM: 134/400 completed | set_idx=33, option=barr_put | total_elapsed=30811.5s
Calculating base
Calculating base finish
Heston FDM: 135/400 completed | set_idx=33, option=van_call | total_elapsed=30862.6s
Calculating base
Calculating base finish
Heston FDM: 136/400 completed | set_idx=33, option=van_put | total_elapsed=30914.8s
Calculating base
Calculating base finish
Heston FDM: 137/400 completed | set_idx=34, option=barr_call | total_elapsed=31266.9s
Calculating base
Calculating base finish
Heston FDM: 138/400 completed | set_idx=34, option=barr_put | total_elapsed=31617.4s
Calculating base
Calculating base finish
Heston FDM: 139/400 completed | set_idx=34, option=van_call | total_elapsed=32017.2s
Calculating base
Calculating base finish
Heston FDM: 140/400 completed | set_idx=34, option=van_put | total_elapsed=32416.0s
Calculating base
Calculating base finish
Heston FDM: 141/400 completed | set_idx=35, option=barr_call | total_elapsed=32487.8s
Calculating base
Calculating base finish
Heston FDM: 142/400 completed | set_idx=35, option=barr_put | total_elapsed=32559.0s
Calculating base
Calculating base finish
Heston FDM: 143/400 completed | set_idx=35, option=van_call | total_elapsed=32640.7s
Calculating base
Calculating base finish
Heston FDM: 144/400 completed | set_idx=35, option=van_put | total_elapsed=32722.6s
Calculating base
Calculating base finish
Heston FDM: 145/400 completed | set_idx=36, option=barr_call | total_elapsed=32801.6s
Calculating base
Calculating base finish
Heston FDM: 146/400 completed | set_idx=36, option=barr_put | total_elapsed=32880.6s
Calculating base
Calculating base finish
Heston FDM: 147/400 completed | set_idx=36, option=van_call | total_elapsed=32970.3s
Calculating base
Calculating base finish
Heston FDM: 148/400 completed | set_idx=36, option=van_put | total_elapsed=33060.5s
Calculating base
Calculating base finish
Heston FDM: 149/400 completed | set_idx=37, option=barr_call | total_elapsed=33225.9s
Calculating base
Calculating base finish
Heston FDM: 150/400 completed | set_idx=37, option=barr_put | total_elapsed=33390.1s
Calculating base
Calculating base finish
Heston FDM: 151/400 completed | set_idx=37, option=van_call | total_elapsed=33575.6s
Calculating base
Calculating base finish
Heston FDM: 152/400 completed | set_idx=37, option=van_put | total_elapsed=33763.2s
Calculating base
Calculating base finish
Heston FDM: 153/400 completed | set_idx=38, option=barr_call | total_elapsed=33882.8s
Calculating base
Calculating base finish
Heston FDM: 154/400 completed | set_idx=38, option=barr_put | total_elapsed=34002.0s
Calculating base
Calculating base finish
Heston FDM: 155/400 completed | set_idx=38, option=van_call | total_elapsed=34138.6s
Calculating base
Calculating base finish
Heston FDM: 156/400 completed | set_idx=38, option=van_put | total_elapsed=34275.2s
Calculating base
Calculating base finish
Heston FDM: 157/400 completed | set_idx=39, option=barr_call | total_elapsed=34381.2s
Calculating base
Calculating base finish
Heston FDM: 158/400 completed | set_idx=39, option=barr_put | total_elapsed=34486.4s
Calculating base
Calculating base finish
Heston FDM: 159/400 completed | set_idx=39, option=van_call | total_elapsed=34607.1s
Calculating base
Calculating base finish
Heston FDM: 160/400 completed | set_idx=39, option=van_put | total_elapsed=34728.5s
Calculating base

           FDM MAE vs MC 100k  FDM MSE vs MC 100k
option
barr_call            0.005371            0.000086
barr_put             0.002167            0.000019
van_call             0.006323            0.000118
van_put              0.006320            0.000118

Reference: result/greeks/mae/0.01915_0.10041_2.43300_h_value_0.01000_0.00019_0.00100_0.02433_hes_delta_mae_mse_100k_details.csv
Saved: result/greeks/mae/hes_fdm_delta_100eta_vs_mc_100k_details.csv
Saved: result/greeks/mae/hes_fdm_delta_100eta_vs_mc_100k_summary.csv

In [12]:
# Heston CVAE-AD delta: 100개 eta, 기존 MC 100k 기준 MAE/MSE
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from IPython.display import display

from e_3_CVAE_greek_AD import CVAE_greeks_AD

HES_AD_N_SAMPLES = 100_000
HES_AD_REPEATS = 30
HES_AD_SEED_STRIDE = 10_000
HES_AD_BARRIER = 0.8
HES_AD_OPTIONS = ("van_call", "van_put", "barr_call", "barr_put")
HES_AD_MC_100K_PATH = Path(
    "result/greeks/mae/"
    "0.01915_0.10041_2.43300_h_value_0.01000_0.00019_0.00100_0.02433_"
    "hes_delta_mae_mse_100k_details.csv"
)

if "hes_cvae" not in globals() or "hes_ckpt" not in globals():
    raise RuntimeError("먼저 Heston CVAE 모델 설정 셀을 실행하세요.")
if np.asarray(hes_para).shape != (100, 7):
    raise ValueError(f"hes_para shape은 (100, 7)이어야 합니다: {np.asarray(hes_para).shape}")

hes_ad_mc_100k = pd.read_csv(HES_AD_MC_100K_PATH)
hes_ad_required_columns = [
    "set_idx", "option", "r", "kappa", "long_var", "xi",
    "corr", "v0", "T", "mc_100k_delta",
]
hes_ad_missing_columns = [
    column for column in hes_ad_required_columns
    if column not in hes_ad_mc_100k.columns
]
if hes_ad_missing_columns:
    raise ValueError(f"MC 100k CSV에 필요한 열이 없습니다: {hes_ad_missing_columns}")
if hes_ad_mc_100k.duplicated(["set_idx", "option"]).any():
    raise ValueError("MC 100k CSV의 set_idx/option 키가 중복되었습니다.")

hes_ad_eta_columns = ["r", "kappa", "long_var", "xi", "corr", "v0", "T"]
hes_ad_reference_eta = (
    hes_ad_mc_100k[["set_idx", *hes_ad_eta_columns]]
    .drop_duplicates()
    .sort_values("set_idx")[hes_ad_eta_columns]
    .to_numpy()
)
if hes_ad_reference_eta.shape != (100, 7) or not np.allclose(
    hes_ad_reference_eta, np.asarray(hes_para), rtol=1e-12, atol=1e-12
):
    raise ValueError("현재 hes_para와 MC 100k 참조 CSV의 eta가 일치하지 않습니다.")

hes_ad_reference = hes_ad_mc_100k.set_index(["set_idx", "option"])[
    "mc_100k_delta"
]
hes_ad_output_dir = Path("result/greeks/mae")
hes_ad_output_dir.mkdir(parents=True, exist_ok=True)
hes_ad_details_path = hes_ad_output_dir / (
    "hes_cvae_ad_delta_100eta_100k_30rep_vs_mc_100k_details.csv"
)
hes_ad_summary_path = hes_ad_output_dir / (
    "hes_cvae_ad_delta_100eta_100k_30rep_vs_mc_100k_summary.csv"
)

# 완료된 eta 결과를 불러와 중단 지점부터 이어서 계산합니다.
if hes_ad_details_path.exists():
    hes_ad_rows = pd.read_csv(hes_ad_details_path).to_dict("records")
    hes_ad_existing = pd.DataFrame(hes_ad_rows)
    completed_set_idxs = set(
        hes_ad_existing.groupby("set_idx").filter(
            lambda group: set(group["option"]) == set(HES_AD_OPTIONS)
        )["set_idx"].astype(int)
    )
    print(f"기존 Heston AD 결과 {len(completed_set_idxs)}/100 eta를 불러왔습니다.")
else:
    hes_ad_rows = []
    completed_set_idxs = set()

hes_ad_started_at = time.perf_counter()
for set_idx, (r, kappa, long_var, xi, corr, v0, T) in enumerate(hes_para):
    if set_idx in completed_set_idxs:
        continue

    eta = (
        1.0, 1.0, float(r), float(kappa), float(long_var),
        float(xi), float(corr), float(v0),
        round(float(T) / MC_DT) * MC_DT,
    )
    ad_values = {option: [] for option in HES_AD_OPTIONS}
    base_seed = 1234 + set_idx * 100

    for repeat_idx in range(HES_AD_REPEATS):
        with warnings.catch_warnings():
            warnings.filterwarnings(
                "ignore",
                message="Hard-indicator AD is a frozen-indicator diagnostic.*",
                category=RuntimeWarning,
            )
            ad_result = CVAE_greeks_AD(
                hes_cvae,
                hes_ckpt,
                eta,
                model_type="hes",
                B=HES_AD_BARRIER,
                greeks=("delta",),
                n_samples=HES_AD_N_SAMPLES,
                antithetic=True,
                seed=base_seed + repeat_idx * HES_AD_SEED_STRIDE,
            )
        for option in HES_AD_OPTIONS:
            ad_values[option].append(ad_result["greeks"]["delta"][option])

    for option, values in ad_values.items():
        ad_delta = float(np.mean(values))
        mc_100k_delta = float(hes_ad_reference.loc[(set_idx, option)])
        error = ad_delta - mc_100k_delta
        hes_ad_rows.append({
            "set_idx": set_idx,
            "option": option,
            "S0": eta[0],
            "K": eta[1],
            "r": eta[2],
            "kappa": eta[3],
            "long_var": eta[4],
            "xi": eta[5],
            "corr": eta[6],
            "v0": eta[7],
            "T": eta[8],
            "mc_100k_delta": mc_100k_delta,
            "cvae_ad_delta": ad_delta,
            "cvae_ad_abs_error_vs_mc_100k": abs(error),
            "cvae_ad_squared_error_vs_mc_100k": error**2,
            "n_samples": HES_AD_N_SAMPLES,
            "repeat_count": HES_AD_REPEATS,
            "barrier": HES_AD_BARRIER if option.startswith("barr_") else None,
            "barrier_estimator": (
                "frozen_indicator_pathwise" if option.startswith("barr_") else None
            ),
        })

    completed_set_idxs.add(set_idx)
    pd.DataFrame(hes_ad_rows).to_csv(hes_ad_details_path, index=False)
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    print(
        f"Heston AD: {len(completed_set_idxs)}/100 eta completed | "
        f"elapsed={time.perf_counter() - hes_ad_started_at:.1f}s",
        flush=True,
    )

hes_ad_details = (
    pd.DataFrame(hes_ad_rows)
    .sort_values(["set_idx", "option"])
    .reset_index(drop=True)
)
if len(hes_ad_details) != 400:
    raise RuntimeError("일부 Heston AD 계산이 완료되지 않았습니다. 셀을 다시 실행하세요.")

hes_ad_mae_mse = (
    hes_ad_details
    .groupby("option", sort=False)[
        ["cvae_ad_abs_error_vs_mc_100k", "cvae_ad_squared_error_vs_mc_100k"]
    ]
    .mean()
    .rename(columns={
        "cvae_ad_abs_error_vs_mc_100k": "CVAE-AD MAE vs MC 100k",
        "cvae_ad_squared_error_vs_mc_100k": "CVAE-AD MSE vs MC 100k",
    })
)
hes_ad_details.to_csv(hes_ad_details_path, index=False)
hes_ad_mae_mse.to_csv(hes_ad_summary_path)

display(hes_ad_mae_mse)
print("주의: barrier AD delta는 frozen-indicator pathwise 추정치입니다.")
print(f"Reference: {HES_AD_MC_100K_PATH}")
print(f"Saved: {hes_ad_details_path}")
print(f"Saved: {hes_ad_summary_path}")

Heston AD: 1/100 eta completed | elapsed=6.1s
Heston AD: 2/100 eta completed | elapsed=12.2s
Heston AD: 3/100 eta completed | elapsed=18.3s
Heston AD: 4/100 eta completed | elapsed=24.4s
Heston AD: 5/100 eta completed | elapsed=30.5s
Heston AD: 6/100 eta completed | elapsed=36.7s
Heston AD: 7/100 eta completed | elapsed=42.7s
Heston AD: 8/100 eta completed | elapsed=48.7s
Heston AD: 9/100 eta completed | elapsed=54.6s
Heston AD: 10/100 eta completed | elapsed=60.6s
Heston AD: 11/100 eta completed | elapsed=66.5s
Heston AD: 12/100 eta completed | elapsed=72.5s
Heston AD: 13/100 eta completed | elapsed=78.4s
Heston AD: 14/100 eta completed | elapsed=84.4s
Heston AD: 15/100 eta completed | elapsed=90.3s
Heston AD: 16/100 eta completed | elapsed=96.2s
Heston AD: 17/100 eta completed | elapsed=102.1s
Heston AD: 18/100 eta completed | elapsed=108.1s
Heston AD: 19/100 eta completed | elapsed=114.0s
Heston AD: 20/100 eta completed | elapsed=120.0s
Heston AD: 21/100 eta completed | elapsed=125.9s
Heston AD: 22/100 eta completed | elapsed=132.0s
Heston AD: 23/100 eta completed | elapsed=138.2s
Heston AD: 24/100 eta completed | elapsed=144.3s
Heston AD: 25/100 eta completed | elapsed=150.3s
Heston AD: 26/100 eta completed | elapsed=156.3s
Heston AD: 27/100 eta completed | elapsed=162.3s
Heston AD: 28/100 eta completed | elapsed=168.5s
Heston AD: 29/100 eta completed | elapsed=174.6s
Heston AD: 30/100 eta completed | elapsed=180.7s
Heston AD: 31/100 eta completed | elapsed=186.8s
Heston AD: 32/100 eta completed | elapsed=192.8s
Heston AD: 33/100 eta completed | elapsed=198.9s
Heston AD: 34/100 eta completed | elapsed=205.0s
Heston AD: 35/100 eta completed | elapsed=211.3s
Heston AD: 36/100 eta completed | elapsed=217.3s
Heston AD: 37/100 eta completed | elapsed=223.4s
Heston AD: 38/100 eta completed | elapsed=229.6s
Heston AD: 39/100 eta completed | elapsed=235.7s
Heston AD: 40/100 eta completed | elapsed=241.7s
Heston AD: 41/100 eta completed | elapsed=247.9s
Heston AD: 42/100 eta completed | elapsed=254.3s
Heston AD: 43/100 eta completed | elapsed=260.6s
Heston AD: 44/100 eta completed | elapsed=266.7s
Heston AD: 45/100 eta completed | elapsed=272.8s
Heston AD: 46/100 eta completed | elapsed=278.9s
Heston AD: 47/100 eta completed | elapsed=285.0s
Heston AD: 48/100 eta completed | elapsed=291.1s
Heston AD: 49/100 eta completed | elapsed=297.4s
Heston AD: 50/100 eta completed | elapsed=303.8s
Heston AD: 51/100 eta completed | elapsed=309.9s
Heston AD: 52/100 eta completed | elapsed=315.9s
Heston AD: 53/100 eta completed | elapsed=321.9s
Heston AD: 54/100 eta completed | elapsed=328.0s
Heston AD: 55/100 eta completed | elapsed=333.9s
Heston AD: 56/100 eta completed | elapsed=340.2s
Heston AD: 57/100 eta completed | elapsed=346.7s
Heston AD: 58/100 eta completed | elapsed=352.8s
Heston AD: 59/100 eta completed | elapsed=359.1s
Heston AD: 60/100 eta completed | elapsed=365.3s
Heston AD: 61/100 eta completed | elapsed=371.5s
Heston AD: 62/100 eta completed | elapsed=377.7s
Heston AD: 63/100 eta completed | elapsed=383.9s
Heston AD: 64/100 eta completed | elapsed=390.0s
Heston AD: 65/100 eta completed | elapsed=396.0s
Heston AD: 66/100 eta completed | elapsed=402.2s
Heston AD: 67/100 eta completed | elapsed=408.4s
Heston AD: 68/100 eta completed | elapsed=414.6s
Heston AD: 69/100 eta completed | elapsed=420.7s
Heston AD: 70/100 eta completed | elapsed=426.9s
Heston AD: 71/100 eta completed | elapsed=433.1s
Heston AD: 72/100 eta completed | elapsed=439.3s
Heston AD: 73/100 eta completed | elapsed=445.4s
Heston AD: 74/100 eta completed | elapsed=451.7s
Heston AD: 75/100 eta completed | elapsed=457.8s
Heston AD: 76/100 eta completed | elapsed=463.8s
Heston AD: 77/100 eta completed | elapsed=469.8s
Heston AD: 78/100 eta completed | elapsed=475.8s
Heston AD: 79/100 eta completed | elapsed=481.8s
Heston AD: 80/100 eta completed | elapsed=487.8s
Heston AD: 81/100 eta completed | elapsed=493.9s
Heston AD: 82/100 eta completed | elapsed=500.1s
Heston AD: 83/100 eta completed | elapsed=506.4s
Heston AD: 84/100 eta completed | elapsed=512.6s
Heston AD: 85/100 eta completed | elapsed=518.8s
Heston AD: 86/100 eta completed | elapsed=525.0s
Heston AD: 87/100 eta completed | elapsed=531.0s
Heston AD: 88/100 eta completed | elapsed=537.1s
Heston AD: 89/100 eta completed | elapsed=543.1s
Heston AD: 90/100 eta completed | elapsed=549.5s
Heston AD: 91/100 eta completed | elapsed=556.0s
Heston AD: 92/100 eta completed | elapsed=562.1s
Heston AD: 93/100 eta completed | elapsed=568.2s
Heston AD: 94/100 eta completed | elapsed=574.3s
Heston AD: 95/100 eta completed | elapsed=580.3s
Heston AD: 96/100 eta completed | elapsed=586.3s
Heston AD: 97/100 eta completed | elapsed=592.3s
Heston AD: 98/100 eta completed | elapsed=598.3s
Heston AD: 99/100 eta completed | elapsed=604.4s
Heston AD: 100/100 eta completed | elapsed=610.7s

           CVAE-AD MAE vs MC 100k  CVAE-AD MSE vs MC 100k
option
barr_call                0.125233                0.026612
barr_put                 0.074844                0.007553
van_call                 0.016565                0.000600
van_put                  0.013855                0.000408

주의: barrier AD delta는 frozen-indicator pathwise 추정치입니다.
Reference: result/greeks/mae/0.01915_0.10041_2.43300_h_value_0.01000_0.00019_0.00100_0.02433_hes_delta_mae_mse_100k_details.csv
Saved: result/greeks/mae/hes_cvae_ad_delta_100eta_100k_30rep_vs_mc_100k_details.csv
Saved: result/greeks/mae/hes_cvae_ad_delta_100eta_100k_30rep_vs_mc_100k_summary.csv

In [37]:
from pathlib import Path

hes_delta_results = pd.DataFrame(hes_delta_rows)
hes_error_specs = (
    ("mc", "10k"),
    ("cvae", "10k"),
)

for method, sample_size in hes_error_specs:
    error = (
        hes_delta_results[f"{method}_{sample_size}_delta"]
        - hes_delta_results["mc_10k_delta"]
    )
    hes_delta_results[f"{method}_{sample_size}_abs_error"] = error.abs()
    hes_delta_results[f"{method}_{sample_size}_squared_error"] = error.pow(2)

hes_summary_columns = {}
for method, sample_size in hes_error_specs:
    hes_summary_columns[f"{method}_{sample_size}_abs_error"] = (
        f"{method.upper()} {sample_size} MAE vs MC (10k mean)"
    )
    hes_summary_columns[f"{method}_{sample_size}_squared_error"] = (
        f"{method.upper()} {sample_size} MSE vs MC (10k mean)"
    )

hes_delta_mae_mse = (
    hes_delta_results
    .groupby("option", sort=False)[list(hes_summary_columns)]
    .mean()
    .rename(columns=hes_summary_columns)
)

mae_output_dir = Path("result/greeks/mae")
mae_output_dir.mkdir(parents=True, exist_ok=True)

first_eta = hes_delta_results.iloc[0]
file_stem = (
    f"{first_eta['r']:.5f}_{first_eta['v0']:.5f}_{first_eta['T']:.5f}_"
    f"h_value_{first_eta['delta_h']:.5f}_{first_eta['rho_h']:.5f}_"
    f"{first_eta['v0_h']:.5f}_{first_eta['theta_h']:.5f}_"
    "hes_delta_mae_mse_10k"
)
details_path = mae_output_dir / f"{file_stem}_details.csv"
summary_path = mae_output_dir / f"{file_stem}_summary.csv"

hes_delta_results.to_csv(details_path, index=False)
hes_delta_mae_mse.to_csv(summary_path)

display(hes_delta_mae_mse)
print(f"MC_REPEATS: {int(hes_delta_results['mc_repeat_count'].iloc[0])}")
print(f"CVAE_REPEATS: {int(hes_delta_results['cvae_repeat_count'].iloc[0])}")
print(f"Saved: {details_path}")
print(f"Saved: {summary_path}")

,MC 10k MAE vs MC (10k mean),MC 10k MSE vs MC (10k mean),CVAE 10k MAE vs MC (10k mean),CVAE 10k MSE vs MC (10k mean)
option,,,,
van_call,0.0,0.0,0.009212,0.000282
van_put,0.0,0.0,0.006873,0.000156
barr_call,0.0,0.0,0.012087,0.000338
barr_put,0.0,0.0,0.004442,0.000063

MC_REPEATS: 30
CVAE_REPEATS: 30
Saved: result/greeks/mae/0.01915_0.10041_2.43300_h_value_0.01000_0.00019_0.00100_0.02433_hes_delta_mae_mse_10k_details.csv
Saved: result/greeks/mae/0.01915_0.10041_2.43300_h_value_0.01000_0.00019_0.00100_0.02433_hes_delta_mae_mse_10k_summary.csv

In [11]:
validate_samples= False
valid_resample  = validate_samples
multiple        = 8

In [ ]:
# Heston CVAE delta: X_T tail 재추출, MC 100k 기준 MAE/MSE
import importlib
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from IPython.display import display

import e_3_CVAE_greek
importlib.reload(e_3_CVAE_greek)
from e_3_CVAE_greek import CVAE_greeks

HES_CVAE_N_SAMPLES = 100_000
HES_CVAE_REPEATS = 30
HES_CVAE_SEED_STRIDE = 10_000
HES_CVAE_MULTIPLE = multiple  # X_T >= log(10), 즉 S_T >= 10*S0이면 재추출
HES_CVAE_OPTIONS = ("van_call", "van_put", "barr_call", "barr_put")
HES_CVAE_MC_100K_DIR = Path("result/greeks/mae")
HES_CVAE_MC_100K_PATTERN = "*_hes_delta_mae_mse_100k_details.csv"

if "hes_cvae" not in globals() or "hes_ckpt" not in globals():
    raise RuntimeError("먼저 Heston CVAE 모델 설정 셀을 실행하세요.")
if np.asarray(hes_para).shape != (100, 7):
    raise ValueError(f"hes_para shape은 (100, 7)이어야 합니다: {np.asarray(hes_para).shape}")
if HES_CVAE_MULTIPLE != 0 and HES_CVAE_MULTIPLE <= 1:
    raise ValueError("HES_CVAE_MULTIPLE은 0 또는 1보다 큰 값이어야 합니다.")

hes_cvae_eta_columns = ["r", "kappa", "long_var", "xi", "corr", "v0", "T"]
hes_cvae_required_columns = [
    "set_idx", "option", "r", "kappa", "long_var", "xi",
    "corr", "v0", "T", "mc_100k_delta",
]
hes_cvae_reference_matches = []
for candidate_path in sorted(HES_CVAE_MC_100K_DIR.glob(HES_CVAE_MC_100K_PATTERN)):
    candidate_df = pd.read_csv(candidate_path)
    if not set(hes_cvae_required_columns).issubset(candidate_df.columns):
        continue
    candidate_eta = (
        candidate_df[["set_idx", *hes_cvae_eta_columns]]
        .drop_duplicates()
        .sort_values("set_idx")[hes_cvae_eta_columns]
        .to_numpy()
    )
    if candidate_eta.shape == (100, 7) and np.allclose(
        candidate_eta, np.asarray(hes_para), rtol=1e-12, atol=1e-12
    ):
        hes_cvae_reference_matches.append((candidate_path, candidate_df))

if len(hes_cvae_reference_matches) != 1:
    raise RuntimeError(
        "현재 hes_para와 일치하는 MC 100k 참조 CSV가 정확히 하나여야 합니다. "
        f"찾은 개수: {len(hes_cvae_reference_matches)}"
    )
HES_CVAE_MC_100K_PATH, hes_cvae_mc_100k = hes_cvae_reference_matches[0]
if hes_cvae_mc_100k.duplicated(["set_idx", "option"]).any():
    raise ValueError("MC 100k CSV의 set_idx/option 키가 중복되었습니다.")

hes_cvae_reference = hes_cvae_mc_100k.set_index(["set_idx", "option"])[
    "mc_100k_delta"
]
hes_cvae_multiple_tag = f"multiple{HES_CVAE_MULTIPLE:g}"
hes_cvae_reference_tag = "_".join(HES_CVAE_MC_100K_PATH.name.split("_")[:3])
hes_cvae_output_dir = Path("result/greeks/mae")
hes_cvae_output_dir.mkdir(parents=True, exist_ok=True)
hes_cvae_details_path = hes_cvae_output_dir / (
    f"hes_cvae_delta_{hes_cvae_reference_tag}_100eta_100k_30rep_"
    f"{hes_cvae_multiple_tag}_vs_mc_100k_details.csv"
)
hes_cvae_summary_path = hes_cvae_output_dir / (
    f"hes_cvae_delta_{hes_cvae_reference_tag}_100eta_100k_30rep_"
    f"{hes_cvae_multiple_tag}_vs_mc_100k_summary.csv"
)

if hes_cvae_details_path.exists():
    hes_cvae_rows = pd.read_csv(hes_cvae_details_path).to_dict("records")
    hes_cvae_existing = pd.DataFrame(hes_cvae_rows)
    completed_set_idxs = set(
        hes_cvae_existing.groupby("set_idx").filter(
            lambda group: set(group["option"]) == set(HES_CVAE_OPTIONS)
        )["set_idx"].astype(int)
    )
    print(f"기존 Heston CVAE 결과 {len(completed_set_idxs)}/100 eta를 불러왔습니다.")
else:
    hes_cvae_rows = []
    completed_set_idxs = set()

hes_cvae_started_at = time.perf_counter()
for set_idx, (r, kappa, long_var, xi, corr, v0, T) in enumerate(hes_para):
    if set_idx in completed_set_idxs:
        continue

    eta = (
        1.0, 1.0, float(r), float(kappa), float(long_var),
        float(xi), float(corr), float(v0),
        round(float(T) / MC_DT) * MC_DT,
    )
    delta_h = max(abs(eta[0]) * 0.01, 1e-6)
    cvae_values = {option: [] for option in HES_CVAE_OPTIONS}
    rejected_fractions = []
    base_seed = 1234 + set_idx * 100

    for repeat_idx in range(HES_CVAE_REPEATS):
        cvae_result = CVAE_greeks(
            hes_cvae,
            hes_ckpt,
            eta,
            model_type="hes",
            B=0.8,
            greeks=("delta",),
            n_samples=HES_CVAE_N_SAMPLES,
            h={"delta": delta_h},
            antithetic=True,
            seed=base_seed + repeat_idx * HES_CVAE_SEED_STRIDE,
            validate_samples=validate_samples,
            valid_resample=valid_resample,
            multiple=HES_CVAE_MULTIPLE,
        )
        for option in HES_CVAE_OPTIONS:
            cvae_values[option].append(cvae_result["greeks"]["delta"][option])
        rejected_fractions.append(
            cvae_result["sampling_diagnostics"]["tail_rejected_sample_fraction"]
        )

    for option, values in cvae_values.items():
        cvae_delta = float(np.mean(values))
        mc_100k_delta = float(hes_cvae_reference.loc[(set_idx, option)])
        error = cvae_delta - mc_100k_delta
        hes_cvae_rows.append({
            "set_idx": set_idx,
            "option": option,
            "S0": eta[0],
            "K": eta[1],
            "r": eta[2],
            "kappa": eta[3],
            "long_var": eta[4],
            "xi": eta[5],
            "corr": eta[6],
            "v0": eta[7],
            "T": eta[8],
            "mc_100k_delta": mc_100k_delta,
            "cvae_100k_delta": cvae_delta,
            "cvae_100k_abs_error_vs_mc_100k": abs(error),
            "cvae_100k_squared_error_vs_mc_100k": error**2,
            "n_samples": HES_CVAE_N_SAMPLES,
            "repeat_count": HES_CVAE_REPEATS,
            "delta_h": delta_h,
            "barrier": 0.8 if option.startswith("barr_") else None,
            "multiple": HES_CVAE_MULTIPLE,
            "X_T_upper": (
                np.log(HES_CVAE_MULTIPLE) if HES_CVAE_MULTIPLE > 0 else np.nan
            ),
            "mean_tail_rejected_fraction": float(np.mean(rejected_fractions)),
        })

    completed_set_idxs.add(set_idx)
    pd.DataFrame(hes_cvae_rows).to_csv(hes_cvae_details_path, index=False)
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    print(
        f"Heston CVAE: {len(completed_set_idxs)}/100 eta completed | "
        f"tail rejected={np.mean(rejected_fractions):.4%} | "
        f"elapsed={time.perf_counter() - hes_cvae_started_at:.1f}s",
        flush=True,
    )

hes_cvae_details = (
    pd.DataFrame(hes_cvae_rows)
    .sort_values(["set_idx", "option"])
    .reset_index(drop=True)
)
if len(hes_cvae_details) != 400:
    raise RuntimeError("일부 Heston CVAE 계산이 완료되지 않았습니다. 셀을 다시 실행하세요.")

hes_cvae_mae_mse = (
    hes_cvae_details
    .groupby("option", sort=False)[
        ["cvae_100k_abs_error_vs_mc_100k", "cvae_100k_squared_error_vs_mc_100k"]
    ]
    .mean()
    .rename(columns={
        "cvae_100k_abs_error_vs_mc_100k": "CVAE 100k MAE vs MC 100k",
        "cvae_100k_squared_error_vs_mc_100k": "CVAE 100k MSE vs MC 100k",
    })
)
hes_cvae_details.to_csv(hes_cvae_details_path, index=False)
hes_cvae_mae_mse.to_csv(hes_cvae_summary_path)

display(hes_cvae_mae_mse)
print(f"X_T 재추출 기준: X_T >= log({HES_CVAE_MULTIPLE:g})")
print(f"Reference: {HES_CVAE_MC_100K_PATH}")
print(f"Saved: {hes_cvae_details_path}")
print(f"Saved: {hes_cvae_summary_path}")

Heston CVAE: 1/100 eta completed | tail rejected=0.0000% | elapsed=1.1s
Heston CVAE: 2/100 eta completed | tail rejected=0.0000% | elapsed=2.1s
Heston CVAE: 3/100 eta completed | tail rejected=0.0000% | elapsed=3.1s
Heston CVAE: 4/100 eta completed | tail rejected=0.0000% | elapsed=4.2s
Heston CVAE: 5/100 eta completed | tail rejected=0.0000% | elapsed=5.2s
Heston CVAE: 6/100 eta completed | tail rejected=0.0000% | elapsed=6.2s
Heston CVAE: 7/100 eta completed | tail rejected=0.0000% | elapsed=7.3s
Heston CVAE: 8/100 eta completed | tail rejected=0.0000% | elapsed=8.3s
Heston CVAE: 9/100 eta completed | tail rejected=0.0000% | elapsed=9.3s
Heston CVAE: 10/100 eta completed | tail rejected=0.0000% | elapsed=10.4s
Heston CVAE: 11/100 eta completed | tail rejected=0.0000% | elapsed=11.4s
Heston CVAE: 12/100 eta completed | tail rejected=0.0000% | elapsed=12.4s
Heston CVAE: 13/100 eta completed | tail rejected=0.0617% | elapsed=14.5s
Heston CVAE: 14/100 eta completed | tail rejected=0.0000% | elapsed=15.5s
Heston CVAE: 15/100 eta completed | tail rejected=0.0000% | elapsed=16.5s
Heston CVAE: 16/100 eta completed | tail rejected=0.0000% | elapsed=17.6s
Heston CVAE: 17/100 eta completed | tail rejected=0.0000% | elapsed=18.6s
Heston CVAE: 18/100 eta completed | tail rejected=0.0000% | elapsed=19.6s
Heston CVAE: 19/100 eta completed | tail rejected=0.0000% | elapsed=20.7s
Heston CVAE: 20/100 eta completed | tail rejected=0.0001% | elapsed=21.8s
Heston CVAE: 21/100 eta completed | tail rejected=0.0000% | elapsed=22.8s
Heston CVAE: 22/100 eta completed | tail rejected=0.0000% | elapsed=23.9s
Heston CVAE: 23/100 eta completed | tail rejected=0.0000% | elapsed=24.9s
Heston CVAE: 24/100 eta completed | tail rejected=0.0000% | elapsed=25.9s
Heston CVAE: 25/100 eta completed | tail rejected=0.0000% | elapsed=27.0s
Heston CVAE: 26/100 eta completed | tail rejected=0.0000% | elapsed=28.0s
Heston CVAE: 27/100 eta completed | tail rejected=0.0000% | elapsed=29.0s
Heston CVAE: 28/100 eta completed | tail rejected=0.0000% | elapsed=30.1s
Heston CVAE: 29/100 eta completed | tail rejected=0.0000% | elapsed=31.1s
Heston CVAE: 30/100 eta completed | tail rejected=0.0000% | elapsed=32.2s
Heston CVAE: 31/100 eta completed | tail rejected=0.0000% | elapsed=33.2s
Heston CVAE: 32/100 eta completed | tail rejected=0.0000% | elapsed=34.2s
Heston CVAE: 33/100 eta completed | tail rejected=0.0156% | elapsed=36.3s
Heston CVAE: 34/100 eta completed | tail rejected=0.0000% | elapsed=37.3s
Heston CVAE: 35/100 eta completed | tail rejected=0.0000% | elapsed=38.3s
Heston CVAE: 36/100 eta completed | tail rejected=0.0000% | elapsed=39.4s
Heston CVAE: 37/100 eta completed | tail rejected=0.0000% | elapsed=40.4s
Heston CVAE: 38/100 eta completed | tail rejected=0.0000% | elapsed=41.4s
Heston CVAE: 39/100 eta completed | tail rejected=0.0000% | elapsed=42.5s
Heston CVAE: 40/100 eta completed | tail rejected=0.0000% | elapsed=43.5s
Heston CVAE: 41/100 eta completed | tail rejected=0.0000% | elapsed=44.5s
Heston CVAE: 42/100 eta completed | tail rejected=0.0000% | elapsed=45.6s
Heston CVAE: 43/100 eta completed | tail rejected=0.0000% | elapsed=46.6s
Heston CVAE: 44/100 eta completed | tail rejected=0.0000% | elapsed=47.6s
Heston CVAE: 45/100 eta completed | tail rejected=0.0000% | elapsed=48.6s
Heston CVAE: 46/100 eta completed | tail rejected=0.0000% | elapsed=49.7s
Heston CVAE: 47/100 eta completed | tail rejected=0.0000% | elapsed=50.7s
Heston CVAE: 48/100 eta completed | tail rejected=0.0000% | elapsed=51.8s
Heston CVAE: 49/100 eta completed | tail rejected=0.0000% | elapsed=52.8s
Heston CVAE: 50/100 eta completed | tail rejected=0.0000% | elapsed=53.8s
Heston CVAE: 51/100 eta completed | tail rejected=0.0000% | elapsed=54.9s
Heston CVAE: 52/100 eta completed | tail rejected=0.0008% | elapsed=56.5s
Heston CVAE: 53/100 eta completed | tail rejected=0.0001% | elapsed=57.8s
Heston CVAE: 54/100 eta completed | tail rejected=0.0000% | elapsed=58.8s
Heston CVAE: 55/100 eta completed | tail rejected=0.0000% | elapsed=59.8s
Heston CVAE: 56/100 eta completed | tail rejected=0.0000% | elapsed=60.9s
Heston CVAE: 57/100 eta completed | tail rejected=0.0000% | elapsed=61.9s
Heston CVAE: 58/100 eta completed | tail rejected=0.0000% | elapsed=62.9s
Heston CVAE: 59/100 eta completed | tail rejected=0.0000% | elapsed=63.9s
Heston CVAE: 60/100 eta completed | tail rejected=0.0000% | elapsed=65.0s
Heston CVAE: 61/100 eta completed | tail rejected=0.0000% | elapsed=66.0s
Heston CVAE: 62/100 eta completed | tail rejected=0.0014% | elapsed=67.9s
Heston CVAE: 63/100 eta completed | tail rejected=0.0000% | elapsed=69.0s
Heston CVAE: 64/100 eta completed | tail rejected=0.0001% | elapsed=70.1s
Heston CVAE: 65/100 eta completed | tail rejected=0.0000% | elapsed=71.1s
Heston CVAE: 66/100 eta completed | tail rejected=0.0000% | elapsed=72.1s
Heston CVAE: 67/100 eta completed | tail rejected=0.0000% | elapsed=73.2s
Heston CVAE: 68/100 eta completed | tail rejected=0.0000% | elapsed=74.2s
Heston CVAE: 69/100 eta completed | tail rejected=0.0000% | elapsed=75.3s
Heston CVAE: 70/100 eta completed | tail rejected=0.0000% | elapsed=76.3s
Heston CVAE: 71/100 eta completed | tail rejected=0.0000% | elapsed=77.4s
Heston CVAE: 72/100 eta completed | tail rejected=0.0000% | elapsed=78.4s
Heston CVAE: 73/100 eta completed | tail rejected=0.0000% | elapsed=79.5s

In [38]:
# Heston delta: 10k 결과를 MC 100k 기준값과 비교
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display

mae_dir = Path("result/greeks/mae")
file_prefix = (
    "0.01915_0.10041_2.43300_h_value_0.01000_0.00019_0.00100_0.02433_"
    "hes_delta_mae_mse"
)
details_10k_path = mae_dir / f"{file_prefix}_10k_details.csv"
details_100k_path = mae_dir / f"{file_prefix}_100k_details.csv"

details_10k = pd.read_csv(details_10k_path)
details_100k = pd.read_csv(details_100k_path)

key_columns = ["set_idx", "option"]
eta_columns = [
    "S0", "K", "r", "kappa", "long_var", "xi", "corr", "v0", "T"
]
required_10k = key_columns + eta_columns + ["mc_10k_delta", "cvae_10k_delta"]
required_100k = key_columns + eta_columns + ["mc_100k_delta"]

missing_10k = [column for column in required_10k if column not in details_10k.columns]
missing_100k = [column for column in required_100k if column not in details_100k.columns]
if missing_10k or missing_100k:
    raise ValueError(
        f"필요한 열이 없습니다. 10k: {missing_10k}, 100k: {missing_100k}"
    )

# set_idx와 option이 같은 행끼리 일대일로 연결합니다.
hes_10k_vs_100k_details = details_10k[required_10k].merge(
    details_100k[required_100k],
    on=key_columns,
    how="inner",
    suffixes=("_10k", "_100k"),
    validate="one_to_one",
)

if len(hes_10k_vs_100k_details) != len(details_10k):
    raise ValueError("10k와 100k 파일에서 일치하지 않는 set_idx/option 행이 있습니다.")

# 두 파일이 동일한 eta 집합을 사용했는지 확인합니다.
for parameter in eta_columns:
    if not np.allclose(
        hes_10k_vs_100k_details[f"{parameter}_10k"],
        hes_10k_vs_100k_details[f"{parameter}_100k"],
        rtol=1e-12,
        atol=1e-12,
    ):
        raise ValueError(f"10k와 100k 파일의 {parameter} 값이 일치하지 않습니다.")

# MC 100k delta를 공통 reference로 사용합니다.
for method in ("mc", "cvae"):
    error = (
        hes_10k_vs_100k_details[f"{method}_10k_delta"]
        - hes_10k_vs_100k_details["mc_100k_delta"]
    )
    hes_10k_vs_100k_details[f"{method}_10k_abs_error_vs_mc_100k"] = error.abs()
    hes_10k_vs_100k_details[f"{method}_10k_squared_error_vs_mc_100k"] = error.pow(2)

metric_columns = {
    "mc_10k_abs_error_vs_mc_100k": "MC 10k MAE vs MC 100k",
    "mc_10k_squared_error_vs_mc_100k": "MC 10k MSE vs MC 100k",
    "cvae_10k_abs_error_vs_mc_100k": "CVAE 10k MAE vs MC 100k",
    "cvae_10k_squared_error_vs_mc_100k": "CVAE 10k MSE vs MC 100k",
}

hes_10k_vs_100k_summary = (
    hes_10k_vs_100k_details
    .groupby("option", sort=False)[list(metric_columns)]
    .mean()
    .rename(columns=metric_columns)
)
overall = (
    hes_10k_vs_100k_details[list(metric_columns)]
    .mean()
    .rename(index=metric_columns)
    .to_frame()
    .T
)
overall.index = ["overall"]
hes_10k_vs_100k_summary = pd.concat([hes_10k_vs_100k_summary, overall])

print("Reference: mc_100k_delta")
display(hes_10k_vs_100k_summary)

Reference: mc_100k_delta

,MC 10k MAE vs MC 100k,MC 10k MSE vs MC 100k,CVAE 10k MAE vs MC 100k,CVAE 10k MSE vs MC 100k
van_call,0.000636,6.589760e-07,0.009287,0.000283
van_put,0.000470,3.349190e-07,0.006912,0.000156
barr_call,0.002230,1.094851e-05,0.011801,0.000317
barr_put,0.001183,2.987293e-06,0.004231,0.000059
overall,0.001130,3.732424e-06,0.008058,0.000204